### PR TITLE
Closes dotnet list reference help text and output #10428

### LINKED ISSUE #10428: dotnet list reference help text and output
## Steps to reproduce
1. `dotnet list reference --help`
2. `dotnet list reference solution-name.sln`
3. `dotnet list reference` on a folder that contains a project with no P2P references

## Expected  behavior
1. It seems that dotnet list reference doesn't accept solution files as a parameter but its description was changed in 2.2 SDK to say it supports solution files. I'd expect that `dotnet list reference --help` wouldn't say that is either a project or solution if solution files aren't supported.
2. I'm assuming this shouldn't work by design. So, fixing the help text would avoid confusions. Or if it's supposed to be supported, then it should list the P2P references from the solution.
3. For a project that has no P2P references, I'd expect a cleaner output, such as:
`There are no project-to-project references in project C:\Users\mairaw\Documents\GitHub\samples\core\getting-started\unit-testing-using-nunit\PrimeService\.`

## Actual behavior
1. `dotnet list reference --help` tells me I can provide a project or solution in .NET Core 2.2 SDK
2. `dotnet list reference solution-name.sln` doesn't work
3. For a project that has no P2P references, the output is a bit garbled. For example:
`There are no Project to Project references in project C:\Users\mairaw\Documents\GitHub\samples\core\getting-started\unit-testing-using-nunit\PrimeService\. ;; Project to Project is the type of the item being requested (project, package, p2p) and C:\Users\mairaw\Documents\GitHub\samples\core\getting-started\unit-testing-using-nunit\PrimeService\ is the object operated on (a project file or a solution file).`

## Environment data
`dotnet --info` output

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    51868761f2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by Jalalx**
This should close #10428 

1. `dotnet list reference --help` output:
```
dotnet list reference --help
Usage: dotnet list <PROJECT> reference [options]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.
```

2. Output of running command on a solution file:
```
dotnet list .\MySolution.sln reference
Project `.\MySolution.sln` is invalid.
Usage: dotnet list <PROJECT> reference [options]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.
```
3. `dotnet list reference` on a folder that contains a project with no P2P references; output:
```
PS C:\Projects\MySolution\src\MyProject.Domain> dotnet list reference
There are no Project to Project references in project C:\Projects\MySolution\src\MyProject.Domain\.
```

Here is `dotnet --info` output:
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010046
 Commit:    77865edb2c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Projects\cli\artifacts\tmp\Debug\dotnet\sdk\3.0.100-preview-010046\

Host (useful for support):
  Version: 3.0.0-preview-27308-3
  Commit:  2f528e5f15

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.1 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010046 [C:\Projects\cli\artifacts\tmp\Debug\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18630-0234 [C:\Projects\cli\artifacts\tmp\Debug\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Projects\cli\artifacts\tmp\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Projects\cli\artifacts\tmp\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Projects\cli\artifacts\tmp\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27308-3 [C:\Projects\cli\artifacts\tmp\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27309-3 [C:\Projects\cli\artifacts\tmp\Debug\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### CODE REVIEW

**Comment by peterhuene** [comment]
Hi @Jalalx.  Thank you for the contribution and for signing the CLA!

I will review this shortly and provide you with any feedback I have.

File: src/dotnet/commands/dotnet-list/ListCommandParser.cs [hunk 1]
```diff
@@ -15,8 +15,8 @@ internal static class ListCommandParser
             LocalizableStrings.NetListCommand,
             Accept.ZeroOrOneArgument()
             .With(
-                    name: CommonLocalizableStrings.SolutionOrProjectArgumentName,
-                    description: CommonLocalizableStrings.SolutionOrProjectArgumentDescription)
+                    name: CommonLocalizableStrings.ProjectArgumentName,
```
Comment (peterhuene) [inline src/dotnet/commands/dotnet-list/ListCommandParser.cs]: Actually, what is the output of `dotnet list --help` with his change?

The problem here is that `dotnet list packages` does support solution files.

Let me see if we can better isolate this change to just the `list reference` command.

Comment (peterhuene) [reply src/dotnet/commands/dotnet-list/ListCommandParser.cs]: Unfortunately it looks like the argument name can't be specialized for the `list reference` subcommand.

What we might want to do is keep this change, but add an additional note to the output of `dotnet list package` that informs users the command also supports solutions.  I'll need to think about this some.

Comment (peterhuene) [reply src/dotnet/commands/dotnet-list/ListCommandParser.cs]: Let's keep this the way you have it.  I have a commit I can push to this PR that will enable support for additional help test from the `dotnet list package` command to show that it can also operate on solution files.  Thanks!

File: src/dotnet/commands/dotnet-list/dotnet-list-reference/LocalizableStrings.resx [hunk 2]
```diff
@@ -124,7 +124,6 @@
     <value>Command to list project to project references</value>
   </data>
   <data name="NoReferencesFound" xml:space="preserve">
-    <value>There are no {0} references in project {1}.
-{0} is the type of the item being requested (project, package, p2p) and {1} is the object operated on (a project file or a solution file). </value>
+    <value>There are no {0} references in project {1}.</value>
```
[the remark this answers is not in the document]
Comment (Jalalx) [reply src/dotnet/commands/dotnet-list/dotnet-list-reference/LocalizableStrings.resx]: Yea, sure

File: src/dotnet/commands/dotnet-list/ListCommandParser.cs (hunk 1 above)
Comment (Jalalx) [reply src/dotnet/commands/dotnet-list/ListCommandParser.cs]: you're welcome! 👍

**Comment by peterhuene** [comment]
Hi @Jalalx.  Thanks for making the requested change from my feedback.

I'm just waiting for confirmation that my proposed change I commented on the issue with is the desired behavior.  If so, I will push up a new commit to this PR and I will ask for your feedback as well as the feedback from the other maintainers.

Once that is reviewed, we'll get this merged in.

**Comment by peterhuene** [comment]
@Jalalx one last minor thing.

Would it be possible for you to reword your commit titles?  We generally use an "imperative form" for a commit title.

For example, I would suggest the following titles for your commits:

* `Fix help description for list command argument.`
* `Simplify help for list reference command on a project without p2p reference.`
* `Remove unused resource key.`

This makes it consistent with a lot of the commits in the repo.

By the way, I've pushed up an additional commit to show just `PROJECT` as the argument to `dotnet list reference`.  I've added the CLI team as additional reviewers.

If you could, please look over 2bd984f4a0909c2a8030f7f2094087a83deddeae and provide me with any feedback or questions you might have.

Thanks!

**Comment by peterhuene** [comment]
It's annoying that me changing my previous review to approved removed the request on the CLI team to review 😞.

**Comment by peterhuene** [comment]
@dotnet/dotnet-cli Could I get a reviewer other than myself to look at the commit I added to the PR? 

It's a bit hacky, to be honest, but it was the simplest way to get a subcommand to modify the argument name and description of the parent command.

**Comment by peterhuene** [comment]
Hi @Jalalx.  Thanks again for the contribution!  Your changes will be included in a future preview of .NET Core 3.0.
