### PR TITLE
Prevent default item glgobing when evaluating run properties.

### LINKED ISSUE #8103: dotnet run is slow in directory with many files
## Steps to reproduce
Create a .net core project, put some `node_modules` in that has tons of files and directories
Move all sources to `src` subdirectory
Put in `<EnableDefaultItems>false</EnableDefaultItems>` to disable msbuild globbing
Put in `<Compile Include="src/**/*.cs"></Compile>` to actually make it compile
Run `dotnet build`
Run `dotnet run`

## Expected  behavior
Build runs fast (since `EnableDefaultItems` prevents msbuild from slowly checking `node_modules`)
Run runs fast (for the same reason as build)

## Actual behavior
Build runs fast
Run runs SUPER SLOW (30 seconds for big `package.json`)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

The fact msbuild tries to traverse all the files by default is already super annoying and staying in the way. However it can be avoided as described in reproduction steps. This however doesn't help too much with `dotnet run` and I don't see why it wouldn't. Looks like a bug?

### PR DESCRIPTION
**Pull request by peterhuene**
When `dotnet run` is executed, a project evaluation occurs to obtain properties
related to running the target executable.  Currently, this evaluation causes
the default item globs to be evaluated.  For project directories containing a
large number of files, this can be a bit performance hit since the globbing
happens twice: once for the build and again for evaluating the run properties.

This commit prevents the globbing from taking place when evaluating the run
properties.

Fixes #8103.

### CODE REVIEW

**Comment by peterhuene** [comment]
I haven't yet figured out a good way to write a test for this, which is why this PR doesn't have a test yet.

Some numbers using a project directory containing 10,000 small files:

Before fix:
```
$ time dotnet run --no-build
Hello World!
dotnet run --no-build  15.72s user 2.28s system 100% cpu 17.950 total
```

After fix:
```
$ time dotnet run --no-build
Hello World!
dotnet run --no-build  0.69s user 0.22s system 101% cpu 0.899 total
```

**Comment by peterhuene** [comment]
@dotnet-bot test Debian8.2 x64 Debug please.

**Comment by peterhuene** [comment]
@dotnet test this please.

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build
@dotnet-bot Test Ubuntu x64 Release Build

File: src/dotnet/commands/dotnet-run/RunCommand.cs [hunk 1]
```diff
@@ -184,6 +184,7 @@ private ICommand GetRunCommand()
         {
             var globalProperties = new Dictionary<string, string>
             {
+                { Constants.EnableDefaultItems,    "false" },
```
Comment (dsplaisted) [inline src/dotnet/commands/dotnet-run/RunCommand.cs]: Add a comment about why this property is set (perf), and why it's safe (we're only evaluating properties, not evaluating items or running targets, so it's not possible that item evaluation would affect the property values).

File: src/dotnet/commands/dotnet-run/RunCommand.cs [hunk 2]
```diff
@@ -197,7 +198,7 @@ private ICommand GetRunCommand()
                 globalProperties.Add("TargetFramework", Framework);
             }
 
-            Project project = new Project(Project, globalProperties, null);
+            var project = new ProjectInstance(Project, globalProperties, null);
```
Comment (dsplaisted) [inline src/dotnet/commands/dotnet-run/RunCommand.cs]: I'm curious, why did this need to change from Project to ProjectInstance?

File: src/dotnet/commands/dotnet-run/RunCommand.cs (hunk 1 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-run/RunCommand.cs]: I'll add a comment explaining the property use.

File: src/dotnet/commands/dotnet-run/RunCommand.cs (hunk 2 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-run/RunCommand.cs]: I was unable to prevent the globbing via the global properties in this manner when using a `Project` vs. a `ProjectInstsance`.  I haven't yet digged into whether or not this is a bug in the MSBuild API; I did check with @rainersigwald first that a `ProjectInstance` should probably be used here anyway.

**Comment by peterhuene** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by peterhuene** [comment]
@dotnet-bot test this please

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@dotnet-bot Test Alpine3.6 x64 Debug Build
@dotnet-bot Test OSX10.12 x64 Release Build

**Comment by peterhuene** [comment]
@MattGertz tell mode ping.
