### PR TITLE
Remove showing firsttime eula for non verbs.

### LINKED ISSUE #3533: First run experience breaks parsing of dotnet --version
## Steps to reproduce
Run dotnet --version

## Expected  behavior
To just have the version of the CLI in the output.

## Actual behavior
We will print the EULA and the offline progress in the output and after that the version, which means that things that rely on simply getting the version out of this command will fail.

We need to consider if we want to skip the First Run experience in some cases for the CLI and we need to decide exactly which those cases are.

cc @blackdwarf @piotrpMSFT @ericstj

### PR DESCRIPTION
**Pull request by Priya91**
fixes #3533 

cc @piotrpMSFT @livarcocc

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@Sokket @brthor take a look as well?

File: src/dotnet/Telemetry.cs [hunk 1]
```diff
@@ -19,6 +20,8 @@ public class Telemetry : ITelemetry
         private Dictionary<string, double> _commonMeasurements = null;
         private Task _trackEventTask = null;
 
+        internal static readonly string TelemetrySentinel  = Path.Combine(ApplicationEnvironment.ApplicationBasePath, $"{Product.Version}.dotnetTelemetry");
```
Comment (ericstj) [inline src/dotnet/Telemetry.cs]: I don't think you can garuntee write permission at ApplicationBasePath.  What if someone extracts to programfiles but then runs as regular user?  Shouldn't we be using either ProgramData or UserProfile/Home for this?

File: src/dotnet/Program.cs [hunk 2]
```diff
@@ -125,6 +126,9 @@ internal static int ProcessArgs(string[] args, ITelemetry telemetryClient)
                 return 1;
             }
 
+            if (telemetryClient == null)
```
Comment (brthor) [inline src/dotnet/Program.cs]: nit: I don't know of any other places where we don't use brackets even for single line statements after `if`

File: src/dotnet/Program.cs [hunk 3]
```diff
@@ -178,6 +182,9 @@ private static void ConfigureDotNetForFirstTimeUse()
                             environmentProvider);
 
                         dotnetConfigurer.Configure();
+
+                        if (!File.Exists(Telemetry.TelemetrySentinel))
```
Comment (brthor) [inline src/dotnet/Program.cs]: same here

File: src/dotnet/Telemetry.cs (hunk 1 above)
Comment (brthor) [inline src/dotnet/Telemetry.cs]: Instead of another sentinel, could we simply reuse the first time sentinel? The first time sentinel gives better guarantees that the telemetry message has been shown and already has guards in place for things like concurrent first invocations.

File: test/dotnet.Tests/GivenThatTheUserIsRunningDoNetForTheFirstTime.cs [hunk 4]
```diff
@@ -28,15 +29,24 @@ static GivenThatTheUserIsRunningDotNetForTheFirstTime()
...
         public void Using_dotnet_for_the_first_time_succeeds()
         {
-            _firstDotnetUseCommandResult.Should().Pass();
+            _firstDotnetNewUseCommandResult.Should().Pass();
+        }
+
+        [Fact]
+        public void Using_dotnet_for_the_first_time_with_non_verbs_doesnt_print_eula()
+        {
+            const string firstTimeUseWelcomeMessage = @".NET Command Line Tools";
```
Comment (brthor) [inline test/dotnet.Tests/GivenThatTheUserIsRunningDoNetForTheFirstTime.cs]: The naming of this variable is somewhat confusing, when I looked at the assertion below I was confused for a bit on why `dotnet --info` would be showing a first time message. Could we rename it to something like `nonVerbHeaderMessage` or something that implies that it's not part of the first time experience.

File: src/dotnet/Program.cs (hunk 3 above)
Comment (brthor) [inline src/dotnet/Program.cs]: With a machine wide installation of dotnet, shared between two users, the first time invoking that machine wide installation for both users will trigger the first time experience, because the cache is user-local by default. 

However, the TelemetrySentinel is dotnet-local so in this case would be machine wide. If one user has gone through first time and seen the first time use message, the TelemetrySentinel will be written. If the second user were not to go through the first time experience, the TelemetrySentinel would still be written and Telemetry would be enabled.

Is that an intended scenario?

File: src/dotnet/Telemetry.cs (hunk 1 above)
Comment (Priya91) [inline src/dotnet/Telemetry.cs]: By firsttime sentinel do you mean the nuget cache sentinel?

Comment (brthor) [inline src/dotnet/Telemetry.cs]: yes, my bad on the naming

File: src/dotnet/Program.cs (hunk 3 above)
Comment (Priya91) [inline src/dotnet/Program.cs]: The nugetcache sentinel is stored at nugetCachepath, and this path is calculated in some order of preference, starting from global.json to runtime dir packages folder. I don't see any logic for where it is being done user local. Can you point to the code ?

File: src/dotnet/Program.cs (hunk 2 above)
Comment (Priya91) [inline src/dotnet/Program.cs]: Corefx default formatting allows for single line if without brackets, but have to use brackets for single line if-else. If that's not the convention for this repo, I can change this

File: src/dotnet/Telemetry.cs (hunk 1 above)
Comment (Priya91) [inline src/dotnet/Telemetry.cs]: NugetCache sentinel is used for creating the nuget cache? Hence the concurrent invocations are an issue, since it's a long operation. I think it's an overkill to reuse that for telemetry, moreover the file.exists guards on trying to create multiple entries, and the concurrency issue with file.create should be handled in file.create.

Comment (Priya91) [inline src/dotnet/Telemetry.cs]: Creating the file in userprofile as @ericstj suggest should also fix this being dotnet-local instead of user-local

File: test/dotnet.Tests/GivenThatTheUserIsRunningDoNetForTheFirstTime.cs (hunk 4 above)
Comment (Priya91) [inline test/dotnet.Tests/GivenThatTheUserIsRunningDoNetForTheFirstTime.cs]: Sure, will change.

File: src/dotnet/Program.cs (hunk 3 above)
Comment (brthor) [inline src/dotnet/Program.cs]: By default the path is `$HOME/.nuget/packages` which is user local.

https://github.com/dotnet/cli/blob/18c8a2724ad066a6999540f5015e1a0ed89b94fc/src/Microsoft.DotNet.ProjectModel/Resolution/PackageDependencyProvider.cs#L159

If global.json or NUGET_PACKAGES is specified then the user has taken some explicit measure to override this.

File: src/dotnet/Telemetry.cs (hunk 1 above)
Comment (brthor) [inline src/dotnet/Telemetry.cs]: @livarcocc took steps to guard against concurrent invocations despite it being a long operaiton. 

How does the Telemetry Sentinel differ in purpose form the nuget cache sentinel?

Comment (brthor) [inline src/dotnet/Telemetry.cs]: If the first time experience is skipped (via` DOTNET_SKIP_FIRST_TIME_EXPERIENCE`), and the message doesn't get shown, should we still enable telemetry?

Comment (Priya91) [inline src/dotnet/Telemetry.cs]: Hmm i see that the first time use notice is printed in the nuget cache sentinel after checking for env variable etc.. and the telemtry should be initialized after this. will reorder

File: test/dotnet.Tests/GivenThatTheUserIsRunningDoNetForTheFirstTime.cs [hunk 5]
```diff
@@ -15,7 +15,8 @@ namespace Microsoft.DotNet.Tests
 {
 	public class GivenThatTheUserIsRunningDotNetForTheFirstTime : TestBase
     {
-        private static CommandResult _firstDotnetUseCommandResult;
+        private static CommandResult _firstDotnetInfoUseCommandResult;
+        private static CommandResult _firstDotnetNewUseCommandResult;
```
Comment (livarcocc) [inline test/dotnet.Tests/GivenThatTheUserIsRunningDoNetForTheFirstTime.cs]: how about you call this _firstDotnetVerbUseCommandResult?
Same for the info, how about _firstDotnetNonVerbUseCommandResult?

File: src/dotnet/Program.cs [hunk 6]
```diff
@@ -78,14 +76,15 @@ public static int Main(string[] args)
             }
         }
 
-        internal static int ProcessArgs(string[] args, ITelemetry telemetryClient)
+        internal static int ProcessArgs(string[] args, ITelemetry telemetryClient = null)
```
Comment (livarcocc) [inline src/dotnet/Program.cs]: Why did we make this change? Where else is this ProcessArgs being used where a telemetryClient is used?

File: src/dotnet/Program.cs (hunk 3 above)
Comment (livarcocc) [inline src/dotnet/Program.cs]: For first run experience, I went to quite some trouble to isolate this logic of manipulating files, etc. Can you take a look at that and use something similar?

We should probably create an abstraction ITelemetrySentinel (like we have for the NuGet cache) and then we can unit test that.

File: src/dotnet/Telemetry.cs (hunk 1 above)
Comment (brthor) [inline src/dotnet/Telemetry.cs]: Okay with the the reordering change, and a user-specific TelemetrySentinel, I think it's fine if they're separate

File: src/dotnet/Program.cs [hunk 7]
```diff
@@ -178,6 +182,9 @@ private static void ConfigureDotNetForFirstTimeUse()
                             environmentProvider);
 
                         dotnetConfigurer.Configure();
+
+                        if (!File.Exists(Telemetry.TelemetrySentinel))
+                            File.Create(Telemetry.TelemetrySentinel);
```
Comment (livarcocc) [inline src/dotnet/Program.cs]: At this point, I don't see what we are gaining from using a separate "sentinel" for telemetry. It is not really set in a different time than the NuGet cache sentinel.

We don't use this other sentinel to not show the EULA or anything like that. Why not keep it simpler and use a single file that is already tested and all? Besides, you can just re-use the sentinel abstraction in the Telemetry.cs file.

File: src/dotnet/Program.cs (hunk 6 above)
Comment (Priya91) [inline src/dotnet/Program.cs]: This processargs is used for unit testing in one of the tests, and it passes a mock telemetry object.

File: src/dotnet/Program.cs (hunk 7 above)
Comment (Priya91) [inline src/dotnet/Program.cs]: Printing the telemetry eula is being clubbed with nuget cache priming, hence this eula will get printed again and again if nuget cache prime fails, since nuget cache sentinel is set only after restore succeeds. Do we want to hve this behavior? or separate the eula from nuget cache priming?

Comment (livarcocc) [inline src/dotnet/Program.cs]: Hum, I see. It makes sense too. However, because the EULA is clubbed with nuget cache priming, if the user sets the SKIP_FIRST_RUN flag, he won't get the EULA and we will still create the telemetry sentinel, right? Not sure that this is the correct behavior.

Maybe we should keep the EULA and its sentinel together. Be it with the nuget prime sentinel, or we separate both. What do you think?

File: src/dotnet/Program.cs (hunk 6 above)
Comment (livarcocc) [inline src/dotnet/Program.cs]: I see. All right.

File: src/dotnet/Program.cs (hunk 7 above)
Comment (Priya91) [inline src/dotnet/Program.cs]: >  if the user sets the SKIP_FIRST_RUN flag, he won't get the EULA and we will still create the telemetry sentinel, right?

Yes that's right, i think the correct way will be to have eula and it's sentinel and then a separate nuget cache sentinel. For now, i am reusing the nuget cahe sentinel for all purposes, we can rethink this design for preview3

File: src/Microsoft.DotNet.Configurer/INuGetCacheSentinel.cs [hunk 8]
```diff
@@ -12,5 +12,7 @@ public interface INuGetCacheSentinel : IDisposable
         bool Exists();
 
         void CreateIfNotExists();
+
+        string SentinelPath { get; }
```
Comment (brthor) [inline src/Microsoft.DotNet.Configurer/INuGetCacheSentinel.cs]: Where is this getting set?

File: src/Microsoft.DotNet.Configurer/NuGetCacheSentinel.cs [hunk 9]
```diff
@@ -30,7 +30,7 @@ private string NuGetCachePath
             }
         }
 
-        private string SentinelPath => Path.Combine(NuGetCachePath, SENTINEL);
+        private string _sentinelPath => Path.Combine(NuGetCachePath, SENTINEL);
```
Comment (livarcocc) [inline src/Microsoft.DotNet.Configurer/NuGetCacheSentinel.cs]: What I would suggest to you here is instead of leaking the path to outside users, just inject the INuGetCacheSentinel as dependency of Telemetry and use INuGetCacheSentinel.Exists() directly there. You won't need this change or many of the other changes below, like making dotnetconfigure return the path to the sentinel, which does not make much sense.

Can you give it a try?

File: src/dotnet/Program.cs [hunk 10]
```diff
@@ -114,6 +114,8 @@ internal static int ProcessArgs(string[] args, ITelemetry telemetryClient)
                 }
                 else
                 {
+                    firstTimeUseSentinelPath = ConfigureDotNetForFirstTimeUse();
```
Comment (eerhardt) [inline src/dotnet/Program.cs]: Looking through the code, we are making a daisy-chain affect with our environment variables.  If I turn off "DOTNET_SKIP_FIRST_TIME_EXPERIENCE", then Telemetry is turned off.  Is this what we want?

Comment (livarcocc) [inline src/dotnet/Program.cs]: In this case, I take it that yes. If the user has not seen the EULA, I imagine we don't want to collect telemetry from her.

Comment (eerhardt) [inline src/dotnet/Program.cs]: Just to call it out - we set "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1" in our CI builds.  Thus we won't get any telemetry in them.

---
In reply to: [67251047](https://github.com/dotnet/cli/pull/3579#discussion_r67251047) [](ancestors = 67251047)

Comment (blackdwarf) [inline src/dotnet/Program.cs]: I don't think this should be the case. Telemetry should be turned off with its own env variable. This is just to skip the text.

File: src/Microsoft.DotNet.Configurer/NuGetCacheSentinel.cs (hunk 9 above)
Comment (Priya91) [inline src/Microsoft.DotNet.Configurer/NuGetCacheSentinel.cs]: Hmm sure, but we have to pass either a nugetcachesentinel object or some other object into the firsttimeconfigure method

File: src/dotnet/Program.cs (hunk 10 above)
Comment (livarcocc) [inline src/dotnet/Program.cs]: @blackdwarf When I chatted with you last week, you said it was ok to use a single environment variable for both scenarios right now, given that they are working hand in hand. What changed that this is no longer good? We are in a time crunch right now, unless we have a very good reason to change this, I would like to push back.

Also, my question was wether it is correct to have telemetry turned off until the user sees the EULA.

File: src/Microsoft.DotNet.Configurer/NuGetCacheSentinel.cs (hunk 9 above)
Comment (livarcocc) [inline src/Microsoft.DotNet.Configurer/NuGetCacheSentinel.cs]: That should be ok. You are going to have to move the using clause for the dotnetsentinel out and pass it in. But I still think that is better than leaking the path information. See how you had to plumb it through so many objects that have no business knowing that information, specially when you have the sentinel available much closer.

**Comment by MichaelSimons** [comment]
From a dotnet Docker perspective I would like an easy way to trigger the cache population without side effects.  We have been using `docker --version`.  Having to run a verb is not desirable in this scenario.

File: src/dotnet/Program.cs [hunk 11]
```diff
@@ -78,14 +76,16 @@ public static int Main(string[] args)
...
-        internal static int ProcessArgs(string[] args, ITelemetry telemetryClient)
+        internal static int ProcessArgs(string[] args, ITelemetry telemetryClient = null)
         {
             // CommandLineApplication is a bit restrictive, so we parse things ourselves here. Individual apps should use CLA.
 
             bool? verbose = null;
             var success = true;
             var command = string.Empty;
             var lastArg = 0;
+            INugetCacheSentinel nugetCacheSentinel = new NugetCacheSentinel();
```
Comment (livarcocc) [inline src/dotnet/Program.cs]: var?

**Comment by livarcocc** [comment]
:shipit: when CI passes

File: src/dotnet/Program.cs (hunk 10 above)
Comment (blackdwarf) [inline src/dotnet/Program.cs]: @livarcocc I think that there was a disconnect somewhere. Let's chat tomorrow in person on this. It got merged now, so if it is to be fixed, it needs to be fixed in the next release.
