### PR TITLE
Fix the paths at which CompileContext locates resgen outputs.

### LINKED ISSUE #1136: Dotnet-resgen does not generate resource. In consequence, dotnet-build will rebuild any project that has resources because of missing outputs
Discovered by https://github.com/dotnet/cli/issues/232#issuecomment-176988459

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #1136

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @pakrym \ @davidfowl

File: test/TestProjects/TestProjectWithResource/Program.cs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+﻿using System;
```
Comment (eerhardt) [inline test/TestProjects/TestProjectWithResource/Program.cs]: FYI - I'm moving the "test\TestProjects" folder to a new top-level directory - "TestAssets". This will be merged shortly.

Comment (eerhardt) [inline test/TestProjects/TestProjectWithResource/Program.cs]: See https://github.com/dotnet/cli/commit/4908436958bb473a9aa610d1893d1c57d7f01851.

**Comment by pranavkm** [comment]
Rebased and updated.

File: TestAssets/TestProjects/TestProjectWithCultureSpecificResource/NuGet.Config [hunk 2]
```diff
@@ -0,0 +1,9 @@
+﻿<?xml version="1.0" encoding="utf-8"?>
```
Comment (eerhardt) [inline TestAssets/TestProjects/TestProjectWithCultureSpecificResource/NuGet.Config]: is there an explicit reason this has its own NuGet.Config?  I have an issue to remove these:  https://github.com/dotnet/cli/issues/1316.  Can you remove it if it isn't needed?

File: TestAssets/TestProjects/TestProjectWithResource/NuGet.Config [hunk 3]
```diff
@@ -0,0 +1,9 @@
+﻿<?xml version="1.0" encoding="utf-8"?>
```
Comment (eerhardt) [inline TestAssets/TestProjects/TestProjectWithResource/NuGet.Config]: Same question as above.

File: TestAssets/TestProjects/TestProjectWithCultureSpecificResource/NuGet.Config (hunk 2 above)
Comment (pranavkm) [inline TestAssets/TestProjects/TestProjectWithCultureSpecificResource/NuGet.Config]: Sure. I think it was because I used an existing test project as a template.

**Comment by pranavkm** [comment]
Updated

File: TestAssets/TestProjects/TestProjectWithCultureSpecificResource/NuGet.Config [hunk 4]
```diff
@@ -3,7 +3,7 @@
   <packageSources>
     <!--To inherit the global NuGet package sources remove the <clear/> line below -->
     <clear />
-    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
+    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
```
Comment (eerhardt) [inline TestAssets/TestProjects/TestProjectWithCultureSpecificResource/NuGet.Config]: This shouldn't be changed.  'dotnet.myget.org' is the new feed and the 'www.myget.org' version will be removed.

Comment (pranavkm) [inline TestAssets/TestProjects/TestProjectWithCultureSpecificResource/NuGet.Config]: Sorry, removed the wrong NuGet.config.

**Comment by eerhardt** [comment]
LGTM

**Comment by pakrym** [comment]
:shipit:
