### PR TITLE
dotnet build fails if the directory contains unicode characters

### LINKED ISSUE #2486: dotnet build fails if the directory contains unicode characters
## Steps to reproduce
    cd /d %USERPROFILE%
    mkdir Tést
    cd Tést
    dotnet new
    dotnet restore
    dotnet build

## Expected  behavior
Build succeeds

## Actual behavior

    Response file 'C:\Users\greggm\T├â┬⌐st\obj\Debug\netcoreapp1.0\dotnet-compile.rsp' doesn't exist.
    C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Users\greggm\T├⌐st\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
    
    Compilation failed.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002330)

Product Information:
 Version:     1.0.0-rc2-002330
 Commit Sha:  3af38bf0fe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

### PR DESCRIPTION
**Pull request by eerhardt**
This fix contains @schellap's fix for https://github.com/dotnet/cli/pull/2673, which is needed to fix this bug and will be rebased out once @schellap merges his change.

Fix #2486 

@brthor @Sridhar-MS @piotrpMSFT

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2680)

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@brthor review this please

File: src/dotnet/Program.cs [hunk 1]
```diff
@@ -138,6 +141,16 @@ internal static int ProcessArgs(string[] args, ITelemetry telemetryClient)
 
         }
 
+        /// <summary>
+        /// Performs initialization that must be done before anything else in the process.
```
Comment (brthor) [inline src/dotnet/Program.cs]: nit: I don't think this comment is necessary, I would infer this from the method name.

File: src/dotnet/Program.cs [hunk 2]
```diff
@@ -138,6 +141,16 @@ internal static int ProcessArgs(string[] args, ITelemetry telemetryClient)
...
+        /// </summary>
+        private static void InitializeProcess()
+        {
+            // by default, .NET Core doesn't have all code pages needed for Console apps.
```
Comment (brthor) [inline src/dotnet/Program.cs]: 👍 for this comment though

File: test/ArgumentForwardingTests/ArgumentForwardingTests.cs [hunk 3]
```diff
@@ -51,6 +51,7 @@ private void FindAndEnsureReflectorPresent()
         /// <param name="testUserArgument"></param>
         [Theory]
         [InlineData(@"""abc"" d e")]
+        [InlineData(@"""ábc"" d é")]
```
Comment (brthor) [inline test/ArgumentForwardingTests/ArgumentForwardingTests.cs]: Although I added this for quick and easy coverage, I think it'd be best to add an explicit unicode fact instead of putting it in this theory. Don't think the PR should block on this though.

**Comment by brthor** [comment]
Didn't review host changes, wasn't sure what was going on there.

Managed changes, couple small comments but :shipit: 

Thanks for fixing this!

File: test/ArgumentForwardingTests/ArgumentForwardingTests.cs (hunk 3 above)
Comment (eerhardt) [inline test/ArgumentForwardingTests/ArgumentForwardingTests.cs]: I'm not sure I follow this fully.  Can you explain a little more what you'd like to see?  What would the fact do that this doesn't?

Also, the `dotnet run` tests exercise this in a more end-to-end manner since dotnet run will spawn the app process, and forward the output back to the CLI.

File: src/dotnet/Program.cs (hunk 1 above)
Comment (eerhardt) [inline src/dotnet/Program.cs]: Removed.

**Comment by eerhardt** [comment]
> Didn't review host changes, wasn't sure what was going on there.

Those were @schellap's fix for #2673.  I needed them for the tests to pass.  Waiting until his change goes in, then I'll rebase and just merge our 3 commits on the managed side.

File: src/dotnet/Program.cs [hunk 4]
```diff
@@ -138,6 +141,16 @@ internal static int ProcessArgs(string[] args, ITelemetry telemetryClient)
...
+            // see the .NET Core Notes in https://msdn.microsoft.com/en-us/library/system.diagnostics.process(v=vs.110).aspx
+            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```
Comment (weshaggard) [inline src/dotnet/Program.cs]: As an FYI System.Text.Encoding.CodePages library is currently only in the shared framework because Roslyn pulls it in and it might not be there in the future which would cause it to be pulled app-local with the CLI because of this (perhaps there are already other dependencies on it as well). That assembly is ~750MB and is intentionally supposed to be pay-for-play, I'm not entirely sure why it is actually needed here as it should be needed to support Unicode encodings.

Comment (weshaggard) [inline src/dotnet/Program.cs]: Reading through some of the other issues I see it appears to be the default Console encoding that is causing the dependency. That is kind of unfortunate that the Console doesn't use a standard algorithm encoding by default.

Comment (eerhardt) [inline src/dotnet/Program.cs]: >  I'm not entirely sure why it is actually needed here as it should be needed to support Unicode encodings.

On my Windows machine, the default code page is:

```
C:\cli>chcp
Active code page: 437
```

Which is not in the default .NET Core code page list.  Similarly, users can set their console code page to whatever they want, and we should be able to work with it, if possible.

Also, another thing we do in the CLI is launch separate processes, and then forward the process's standard error and out to our process, and interpret it. One example of this is when we run `csc.exe`, we Regex the output looking for compiler warnings and errors so we can count them up at the end. Another is when we launch the user's app, we forward the output to our output during `dotnet run`. The separate process can use whatever code page it wants to write to its standard out. If we don't have the correct code page, we won't be reading the results correctly.

Looking at my machine, the System.Text.Encoding.CodePages.dll is 852 **K**B.

/cc @tarekgh

**Comment by eerhardt** [comment]
test OSX x64 Release Build

File: test/ArgumentForwardingTests/ArgumentForwardingTests.cs (hunk 3 above)
Comment (brthor) [inline test/ArgumentForwardingTests/ArgumentForwardingTests.cs]: The fact wouldn't do anything the theory doesn't, so from that perspective, there's not much value. 

The value I see in the separation is better readability of the expectations. This essentially tests that we round trip arguments properly when doing process jumps. Having the fact would just make it clear that we are testing unicode is round tripped right. 

Ultimately it's a fit/finish thing, and I don't feel too strongly that it needs to move.

**Comment by eerhardt** [comment]
test OSX x64 Release Build
test Windows_NT x86 Debug Build
