### PR TITLE
Ignore desktop framework in the MultiProjectValidator

### LINKED ISSUE #754: MultiProjectValidator Crashing on Ubuntu
This is the error I am seeing:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ProjectSanity.AnalysisRules.DependencyMismatch.DependencyInfo.Create(ProjectContext context, LibraryDescription library)
   at MultiProjectValidator.AnalysisRules.DependencyMismatchRule.CreateDependencyGroups(List`1 projectContexts)
   at MultiProjectValidator.AnalysisRules.DependencyMismatchRule.EvaluateProjectContextTargetGroup(List`1 targetProjectContextGroup)
   at MultiProjectValidator.AnalysisRules.DependencyMismatchRule.EvaluateProjectContextTargetGroups(Dictionary`2 targetGroupedProjectContexts)
   at MultiProjectValidator.AnalysisRules.DependencyMismatchRule.Evaluate(List`1 projectContexts)
   at MultiProjectValidator.ProjectAnalyzer.DoAnalysis()
   at MultiProjectValidator.Program.Main(String[] args)
Aborted (core dumped)
```

This is being caused by the "net451" framework option in https://github.com/dotnet/cli/blob/master/src/Microsoft.Extensions.DependencyModel/project.json

The Validator is picking up mscorlib which seems to have no version.

As a solution I plan to disable the MultiProjectValidator on desktop target frameworks. It doesn't make much sense for the purpose of this tool anyways.

### PR DESCRIPTION
**Pull request by brthor**
Fixes #754

### CODE REVIEW

File: tools/MultiProjectValidator/ProjectLoader.cs [hunk 1]
```diff
@@ -29,10 +30,23 @@ private static List<ProjectContext> LoadProjectContexts(string[] projectFiles)
...
+                    {
+                        projectContexts.Add(context);
+                    }
+                }  
             }
 
             return projectContexts;
         }
+
+        private static bool TargetIsDesktop(ProjectContext context)
```
Comment (livarcocc) [inline tools/MultiProjectValidator/ProjectLoader.cs]: This seems weird to be here. I think. This is called project loader, but it will skip one because it can't be validated. Should the validator be the one skipping it?! You could have an extension method in the project context, something like SkipProjectValidation where you could put this check.

Comment (brthor) [inline tools/MultiProjectValidator/ProjectLoader.cs]: Yeah I see what you were saying here. 

This portion of the code is responsible for loading all of the contexts and shouldn't be making a decision on which ones should/shouldn't be validated.

I don't know if an extension method is the right place either. To me it would make more sense if the individual Analysis Rules determined whether or not they should be skipping a context. So I would add this logic to https://github.com/dotnet/cli/blob/master/tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs

Thoughts?

File: tools/MultiProjectValidator/ProjectLoader.cs [hunk 2]
```diff
@@ -6,7 +6,8 @@ namespace MultiProjectValidator
 {
     public class ProjectLoader
     {
-        private static readonly string PROJECT_FILENAME = "project.json";
+        private static readonly string s_desktopTfmPrefix = ".NETFramework";
```
Comment (piotrpMSFT) [inline tools/MultiProjectValidator/ProjectLoader.cs]: static fields should be named with a leading capital letter and without s_.

File: tools/MultiProjectValidator/ProjectLoader.cs (hunk 1 above)
Comment (piotrpMSFT) [inline tools/MultiProjectValidator/ProjectLoader.cs]: both? The rule should decide if there are contexts it doesn't care about, but something tied to Context should probably determine if that context is desktop...

File: tools/MultiProjectValidator/ProjectLoader.cs (hunk 2 above)
Comment (brthor) [inline tools/MultiProjectValidator/ProjectLoader.cs]: Getting some conflicting guidance here: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

File: tools/MultiProjectValidator/ProjectLoader.cs (hunk 1 above)
Comment (brthor) [inline tools/MultiProjectValidator/ProjectLoader.cs]: Alright that makes more sense. I like this approach

**Comment by brthor** [comment]
@livarcocc @piotrpMSFT Feedback taken into account, PTAL

File: tools/MultiProjectValidator/ProjectLoader.cs (hunk 2 above)
Comment (brthor) [inline tools/MultiProjectValidator/ProjectLoader.cs]: Although I prefer your way. `s_` looks ugly :(

File: tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs [hunk 3]
```diff
@@ -3,24 +3,30 @@
...
+            var pass = failureMessages.Count() == 0;
 
             var result = new AnalysisResult(failureMessages, pass);
             return result;
         }
 
-        private List<string> EvaluateProjectContextTargetGroups(Dictionary<string, List<ProjectContext>> targetGroupedProjectContexts)
+        private IEnumerable<ProjectContext> FilterContextList(IEnumerable<ProjectContext> projectContexts)
+        {
+            return projectContexts.Where(context=> !context.TargetIsDesktop()).Select(context => context);
```
Comment (livarcocc) [inline tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs]: Why do you need the select after the where clause?!

File: tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs [hunk 4]
```diff
@@ -3,24 +3,30 @@
...
-        public AnalysisResult Evaluate(List<ProjectContext> projectContexts)
+        public AnalysisResult Evaluate(IEnumerable<ProjectContext> projectContexts)
         {
-            var targetGroupedContexts = GroupContextsByTarget(projectContexts);
+            var filteredContexts = FilterContextList(projectContexts);
+            var targetGroupedContexts = GroupContextsByTarget(filteredContexts);
 
             var failureMessages = EvaluateProjectContextTargetGroups(targetGroupedContexts);
-            var pass = failureMessages.Count == 0;
+            var pass = failureMessages.Count() == 0;
```
Comment (livarcocc) [inline tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs]: Why not move this pass logic inside the AnalysisResult class itself?

**Comment by livarcocc** [comment]
Some minor things that you can take a look at, but overall, LGTM.

File: tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs (hunk 3 above)
Comment (brthor) [inline tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs]: My mental model of LINQ is mostly based of SQL :smile: 

Will make the change.

File: tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs (hunk 4 above)
Comment (brthor) [inline tools/MultiProjectValidator/AnalysisRules/DependencyMismatchRule.cs]: The `_messages` object in Analysis Result is intended to be general purpose (including messages which might not indicate failure). For that reason I think it's reasonable to rely on the rule to determine whether or not it passed. In this case it's an implementation detail of the rule that the presence of a message indicates failure.

**Comment by brthor** [comment]
ci is back :) Logs look good, merging
