### PR TITLE
Check if project.json exists before creating new project in the same dir

### LINKED ISSUE #3499: Running dotnet new --type xunittest breaks project
## Steps to reproduce
1) Create a new C# project folder
    a) mkdir Testing
    b) cd Testing
    c) dotnet new
2) Add xunit testing capabilities in the same folder
   a) dotnet new --type xunittest

## Expected  behavior
Unit test files are added

## Actual behavior
```
[bb@bb-oraclelinux72 testing]$ ../dotnet/dotnet new --type xunittest
The file '/home/bb/testing/project.json' already exists.
Creating new C# project failed.
```

The project is then changed such that it no longer compiles

## Environment data
`dotnet --info` output:

[bb@bb-oraclelinux72 testing]$ ../dotnet/dotnet --info
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     ol
 OS Version:  7.2
 OS Platform: Linux
 RID:         ol.7.2-x64

### PR DESCRIPTION
**Pull request by Priya91**
Fixes #3499 

cc @livarcocc @piotrpMSFT

### CODE REVIEW

File: src/dotnet/commands/dotnet-new/Program.cs [hunk 1]
```diff
@@ -26,6 +26,12 @@ private static string GetFileNameFromResourceName(string s)
 
         public int CreateEmptyProject(string languageName, string templateDir)
         {
+            if (File.Exists(Path.Combine(Directory.GetCurrentDirectory(), "project.json")))
+            {
+                Reporter.Error.WriteLine($"Creating new {languageName} project failed, project.json already exists.");
```
Comment (livarcocc) [inline src/dotnet/commands/dotnet-new/Program.cs]: @blackdwarf Should we voice this out like this? Or should we say folder already contains a project in it? Also, is this enough check or should we check if the current folder is empty (I particularly don't like this check in VS, btw).

**Comment by livarcocc** [comment]
@Priya91 We have a dotnet-new.Tests project, can you create a test there for this?

File: src/dotnet/commands/dotnet-new/Program.cs (hunk 1 above)
Comment (Priya91) [inline src/dotnet/commands/dotnet-new/Program.cs]: A better check would be to see if any of the extracted zip entries is already there in the folder, for which it will fail..

Comment (blackdwarf) [inline src/dotnet/commands/dotnet-new/Program.cs]: The second check, if there are files in the folder. Also, there should be a message that says that the projects already exists in the local folder and shouldn't mention `project.json` for any reason.

Comment (Priya91) [inline src/dotnet/commands/dotnet-new/Program.cs]: @blackdwarf Can you review the recent changes.. The message indicates why the project creation failed with exactly which filename that's conflicting. Since the concept of a project is very hazy, is a collection of code files under a directory project, or does the presence of project.json make it a project..

**Comment by Priya91** [comment]
@dotnet-bot test Ubuntu x64 Release Build

File: test/dotnet-new.Tests/GivenThatIWantANewCSApp.cs [hunk 2]
```diff
@@ -52,6 +52,21 @@ public void When_dotnet_build_is_invoked_Then_project_builds_without_warnings()
             buildResult.Should().Pass();
             buildResult.Should().NotHaveStdErr();
         }
+
+        [Fact]
+        public void When_dotnet_new_is_invoked_mupliple_times()
```
Comment (brthor) [inline test/dotnet-new.Tests/GivenThatIWantANewCSApp.cs]: a common pattern we usually use is to include the expectation of the test result in the the name, so for example you could add `_should_fail` here

File: test/dotnet-new.Tests/GivenThatIWantANewCSApp.cs [hunk 3]
```diff
@@ -52,6 +52,21 @@ public void When_dotnet_build_is_invoked_Then_project_builds_without_warnings()
...
+            var rootPath = Temp.CreateDirectory().Path;
+
+            new TestCommand("dotnet") { WorkingDirectory = rootPath }
+                .Execute("new");
+
+            var result = new TestCommand("dotnet") { WorkingDirectory = rootPath }
+                .ExecuteWithCapturedOutput("new");
+
+            result.Should().Fail();
+            result.Should().HaveStdErr();
```
Comment (brthor) [inline test/dotnet-new.Tests/GivenThatIWantANewCSApp.cs]: Given that the bug also had instances of dotnet new modifying the files placed by the previous invocation, could we add logic to ensure that the files weren't modified between runs in this test?

**Comment by brthor** [comment]
Nice! :shipit: when green

**Comment by brthor** [comment]
```
12:13:48 [39;49mBuild failed: Microsoft.DotNet.Cli.Build.Framework.BuildFailureException: Command failed with exit code 139: /opt/code/artifacts/ubuntu.14.04-x64/stage2/dotnet "build" "--configuration" "Release"
```

@eerhardt @sergiy-k

**Comment by eerhardt** [comment]
It was using old Runtime.CoreCLR:

```
12:05:03 log  : Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.2-rc3-24210-01.
```
since it was run before we merged in the stable versions.

Re-running will fix it.

test Ubuntu x64 Release Build

**Comment by brthor** [comment]
Hmmm How did the old coreclr come in

File: src/dotnet/commands/dotnet-new/Program.cs [hunk 4]
```diff
@@ -26,6 +26,13 @@ private static string GetFileNameFromResourceName(string s)
 
         public int CreateEmptyProject(string languageName, string templateDir)
         {
+            // Check if project.json exists in the folder
+            if (File.Exists(Path.Combine(Directory.GetCurrentDirectory(), "project.json")))
```
Comment (joshfree) [inline src/dotnet/commands/dotnet-new/Program.cs]: should "project.json" be a static readonly var here instead of a hardcoded string literal?

**Comment by joshfree** [comment]
LGTM

File: src/dotnet/commands/dotnet-new/Program.cs (hunk 4 above)
Comment (eerhardt) [inline src/dotnet/commands/dotnet-new/Program.cs]: There is already a constant for it:  https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/src/Microsoft.DotNet.ProjectModel/Project.cs#L16

Comment (Priya91) [inline src/dotnet/commands/dotnet-new/Program.cs]: Can be a readonly static, it was used as a string literal in other places in the file.
