### PR TITLE
Suppress output from `dotnet run` when using quiet verbosity level.

### LINKED ISSUE #9545: Verbosity level is ignored for launchSettings.json
## Steps to reproduce
```powershell
dotnet new console -n netcli-issue
cd .\netcli-issue\
mkdir Properties
'{"profiles": {"netcli-issue": {"commandName": "Project"}}}' > .\Properties\launchSettings.json
dotnet run --verbosity quiet
```

## Expected  output
Hello World!

## Actual output
Using launch settings from C:\doc\src\tmp\netcli-issue\netcli-issue\Properties\launchSettings.json...
Hello World!

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### PR DESCRIPTION
**Pull request by peterhuene**
This commit suppresses the output that is displayed by the `dotnet run` command
when launch settings are being used, unless the verbosity level is above
"quiet".

Fixes #9545.

### CODE REVIEW

File: src/dotnet/commands/dotnet-run/RunCommand.cs [hunk 1]
```diff
@@ -26,6 +26,10 @@ public partial class RunCommand
 
         private List<string> _args;
         private bool ShouldBuild => !NoBuild;
+        private bool HasQuietVerbosity =>
+            RestoreArgs.All(arg => !arg.StartsWith("-verbosity:") ||
```
Comment (nguerrera) [inline src/dotnet/commands/dotnet-run/RunCommand.cs]: We should use StringComparison.Ordinal here.

Comment (peterhuene) [reply src/dotnet/commands/dotnet-run/RunCommand.cs]: I'll fix.

Comment (peterhuene) [reply src/dotnet/commands/dotnet-run/RunCommand.cs]: Pushed.
