### PR TITLE
Fixing the name of the OS X package

### LINKED ISSUE #1537: Latest and versioned package names for OS X are different
The latest package is named `dotnet-osx-x64.latest.pkg`. However, the versioned package is called `dotnet-osx-x64-cli.[version].pkg`. 

The expected behavior is that they should be the same. There is probably a bug somewhere in the publish scripts on naming.

/cc @Sridhar-MS @piotrpMSFT @anurse

### PR DESCRIPTION
**Pull request by blackdwarf**
There was a bug in naming the versioned PKG for OSX when it is being packaged. This resulted
in two different names for the latest and versioned, which is not what we want.

Fix #1537 

/cc @glennc @Sridhar-MS @piotrpMSFT

### CODE REVIEW

**Comment by Sridhar-MS** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
What does this affect? Will int Impact file name? Url? Upgrades?

**Comment by blackdwarf** [comment]
@piotrpMSFT this affects the versioned (e.g. dotnet-osx-x64.[version].pkg) filename. Currently, this file is named `dotnet-cli-x64.[version].pkg` which is not the case with other installers (such as EXE). This PR fixes that to be in line with others.

The URLs that need to change are mostly on the "Getting Started" page on dotnet.github.io. The README.md URLs point to latest, IINHM.

**Comment by blackdwarf** [comment]
@piotrpMSFT you ok with merging this? Seems like the checks have cleared and whatnot.

File: packaging/osx/package-osx.sh [hunk 1]
```diff
@@ -28,7 +28,7 @@ fi
 PACKAGE_DIR=$REPOROOT/artifacts/packages/pkg
 [ -d "$PACKAGE_DIR" ] || mkdir -p $PACKAGE_DIR
 
-PACKAGE_NAME=$PACKAGE_DIR/dotnet-cli-x64.${DOTNET_CLI_VERSION}.pkg
+PACKAGE_NAME=$PACKAGE_DIR/dotnet-osx-x64.${DOTNET_CLI_VERSION}.pkg
```
Comment (eerhardt) [inline packaging/osx/package-osx.sh]: While you are in here, would you mind changing all the places in the script where this name is duplicated? That way we don't have this issue going forward?  I see two places below where this name is copied.

**Comment by blackdwarf** [comment]
@dotnet-bot test Windows_2016 Debug Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test Windows_2016 Release Build please

File: packaging/osx/package-osx.sh (hunk 1 above)
Comment (blackdwarf) [inline packaging/osx/package-osx.sh]: Okkie, new version coming up.

**Comment by blackdwarf** [comment]
@dotnet-bot test OSX Debug Build please

**Comment by eerhardt** [comment]
LGTM

**Comment by blackdwarf** [comment]
@Sridhar-MS @piotrpMSFT you ok with the change? Shall I merge?? </maniacal_evil_laugh>

**Comment by Sridhar-MS** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
:shipit:
