### PR TITLE
Remove temp project path from tool install warnings and errors.

### LINKED ISSUE #8707: Tool install with nuget error should not display the temp project in output
## Steps to reproduce

See related issue #8698.

```
dotnet install tool Microsoft.Dotnet.Watcher.Tools -g
```

## Expected  behavior

The temp project path should not appear in the output by default:

```
$ dotnet install tool Microsoft.Dotnet.Watcher.Tools -g
error NU1212: Invalid project-package combination for Microsoft.DotNet.Watcher.Tools 2.0.0. DotnetToolReference project style can only contain references of the DotnetTool type
The tool package could not be restored.
Tool 'Microsoft.Dotnet.Watcher.Tools' failed to install.
```

## Actual behavior

The temp project path appears in the output:

```
$ dotnet install tool Microsoft.Dotnet.Watcher.Tools -g
/var/folders/rl/m1rv1rxd643gpwspqrbxy76r0000gn/T/w1heen5l.wc5/yh505uu5.u4i.csproj : error NU1212: Invalid project-package combination for Microsoft.DotNet.Watcher.Tools 2.0.0. DotnetToolReference project style can only contain references of the DotnetTool type
The tool package could not be restored.
Tool 'Microsoft.Dotnet.Watcher.Tools' failed to install.
```

## Environment data
```
$ dotnet --info
.NET Command Line Tools (2.1.300-preview2-008266)

Product Information:
 Version:            2.1.300-preview2-008266
 Commit SHA-1 hash:  6fb919f433

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /Users/peterhuene/src/cli/bin/2/osx-x64/dotnet/sdk/2.1.300-preview2-008266/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26131-06
  Build    : b13a0d5c331f374afd35ded57b9a4b4ab128864c
```

### PR DESCRIPTION
**Pull request by peterhuene**
This commit attempts to filter the diagnostic messages emitted during tool
installation.  The diagnostic messages may be prefixed with the temporary
project; since this is an implementation detail that only causes confusion and
clutter in the diagnostic messages, the prefix is removed if present.

Fixes #8707.

### CODE REVIEW

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs [hunk 1]
```diff
@@ -69,5 +69,28 @@ public ProjectRestorer(IReporter reporter = null)
                 throw new ToolPackageException(LocalizableStrings.ToolInstallationRestoreFailed);
             }
         }
+
+        private static void WriteLine(IReporter reporter, string line, FilePath project)
+        {
+            line = line ?? "";
+
+            // Remove the temp project prefix if present
+            if (line.StartsWith($"{project.Value} : ", StringComparison.CurrentCultureIgnoreCase))
```
Comment (nguerrera) [inline src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: Why CurrentCulture?

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs [hunk 2]
```diff
@@ -69,5 +69,28 @@ public ProjectRestorer(IReporter reporter = null)
...
+            {
+                line = line.Substring(project.Value.Length + 3);
```
Comment (nguerrera) [inline src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: This math may be wrong for some cultures.

Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: I assume you mean the `project.Value.Length` and this should use a `StringInfo` to arrive at the correct length?

Comment (nguerrera) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: Well, I mean if we need to compare to project.Value by CurrentCulture. If we can check for project.Value at start with Ordinal, then this is fine. It is related to my other comment.

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 1 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: I wanted to guard against MSBuild outputting a different case for the project file path (I don't think it will given how we construct the path, but for case-insensitive file systems it wouldn't be "wrong" to do so).

However, I don't think an ordinal or invariant comparison would give the desired result.

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 2 above)
Comment (nguerrera) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: Do we have full control over project.Value? Will it have characters outside the ASCII range. Who puts that ' : ' is it also not localized like 'error' and 'warning'?

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 1 above)
Comment (nguerrera) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: The correct way to compare paths like the Windows file system is OrdinalIgnoreCase.

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 2 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: We do have control over the project path, but it is based on `Path.GetTempPath`.

The ` : ` comes from the format MSBuild uses for its console diagnostic messages.  Likewise, `warning` and `error` are intentionally not localized, presumably so that the level can be parsed in a manner like what is being done here.

Comment (nguerrera) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: I think we can just use OrdinalIgnoreCase, then.

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 1 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: And is that also true of case-insensitive APFS?

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 2 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: I'm fine with `OrdinalIgnoreCase` as a safe-guard (I suspect `Ordinal` would work too provided MSBuild doesn't try to normalize the path given).

Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: Changed to `OrdinalIgnoreCase`.

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs [hunk 3]
```diff
@@ -56,11 +56,11 @@ public ProjectRestorer(IReporter reporter = null)
             var command = new DotNetCommandFactory(alwaysRunOutOfProc: true)
                 .Create("restore", argsToPassToRestore);
 
-            if (_reporter != null)
+            if (verbosity == null || _reporter != null)
             {
                 command = command
-                    .OnOutputLine((line) => _reporter.WriteLine(line))
-                    .OnErrorLine((line) => _reporter.WriteLine(line));
+                    .OnOutputLine(line => WriteLine(_reporter ?? Reporter.Output, line, project))
```
Comment (wli3) [inline src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: _reporter should not be null after constructor, if so could you fix it?

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 2 above)
Comment (nguerrera) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: 👍

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 3 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: `_reporter` can't default to a single value because output from `STDERR` should go to `Reporter.Error` and not `Reporter.Output`.  So we would need two fields.  I'd prefer one that says "direct all output to this reporter".

Actually, this just reminded me that your `tool-path` refactoring is now passing in `Reporter.Output` in the constructor where previously it was only being used for tests.  This breaks stderr output.

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 1 above)
Comment (nguerrera) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: I don't know.

File: src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs (hunk 3 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: Additionally, we'd need another flag field to indicate whether or not the original reporter passed in the constructor was null or not (if it's non-null then output must be redirected).  It's much simpler to allow the field to be null, imo.  But if you feel strongly about it, I could change to these fields:

```
        private readonly IReporter _reporter;
        private readonly IReporter _errorReporter;
        private readonly bool _forceOutputRedirection;
```

Comment (peterhuene) [reply src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs]: I decided to fix it as describe.  I've pushed up the change.

**Comment by peterhuene** [comment]
The RHEL failure occurred again (from the `list tool` command changes, this now manifests as a "failure to locate the staged package" following the restore).  As a theory, I've pushed up a commit to remove the reliance of setting the current working directory from the tool package installer tests in the hopes of improving the stability of the tests.

I still need to setup a RHEL VM to see if I can manually reproduce the failure with what I suspect the issue to be.

**Comment by peterhuene** [comment]
Oh right, the broken much implementation on Windows when using TempRoot. Let me fix good that.

**Comment by peterhuene** [comment]
I tracked down the Windows failure to `TempRoot.Root` containing both `/` (including a double `//`) and `\` in the path.  This caused the mock file system to enumerate incorrectly because no path normalization was being performed and certain `Path` functions were returning differing results from what was stored in the internal `Dictionary`.

I first attempted to fix the mock file system to try to normalize all the path interactions, but this was a more invasive change that impacted other tests.  I decided to just normalize the use of `TempRoot.Root` to fix this particular issue.

@nguerrera @wli3 can you review the second commit that was pushed?  Hopefully it will bring some stability to the tool package installer tests.

**Comment by nguerrera** [comment]
Second commit looks good. Thanks.

**Comment by wli3** [comment]
ack, let me check

**Comment by wli3** [comment]
Good to go, but not perfect.

https://github.com/dotnet/cli/pull/8734/commits/52478e8947d12953119ebf6175adaa0166a7558f#diff-514fdb6bf1ab21b1a21adfd2ccf82145R121  is a test induced design damage. And the test is just testing the nuget flag. I do think use a test to lock nuget's behavior that we depend on is important since they are in rapid development. A regression is very likely. But adding another optional just for test making it further away from production.

Let me also see if there is other alternative. One way is to make is closer to real. Find a better mock library. Or make is less dependent on file system state.

**Comment by wli3** [comment]
I mean please checkin. I'll keep digging on my own

**Comment by peterhuene** [comment]
Agreed, an option just for testing purposes is not ideal. Let's work out a proper solution after this change.
