### PR TITLE
Fixing publish scripts to only push to Latest when all bits are there

### LINKED ISSUE #2613: CLI Builds should publish when all builds are finished
## Steps to reproduce
go to https://github.com/dotnet/cli

## Expected  behavior
All versions are the same

## Actual behavior
Builds get out of sync, so you will have fixes on one OS but not on others.

### PR DESCRIPTION
**Pull request by sokket**
Fixes #2613  by waiting until all the current build number bits are available before pushing to the Latest blob storage

/cc @piotrpMSFT

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2703)

### CODE REVIEW

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 1]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
         [Environment("PUBLISH_TO_AZURE_BLOB", "1", "true")] // This is set by CI systems
         public static BuildTargetResult Publish(BuildTargetContext c)
         {
+            if (ShouldPublishToLatest())
+            {
+                string targetContainer = $"{Channel}/Binaries/Latest/";
+
+                foreach (string blob in _latestBlobs)
```
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: {}

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 2]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
...
+                    AzurePublisherTool.CopyBlob(blob.Replace("/dotnet/", ""), (targetContainer + Path.GetFileName(blob)).Replace(CliNuGetVersion, "latest").Replace(SharedFrameworkNugetVersion, "latest"));
```
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: make this more readable?

Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: this is a bit hard to read. perhaps:

````
var blobUrl = blob.Replace(...)
                            .Replace(...)
                            .Replace(...)...
````

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 3]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
...
+
+                PublishLatestCliVersionTextFile(c);
+                PublishLatestSharedFrameworkVersionTextFile(c);
+            }
+
             return c.Success();
         }
 
+        private static bool ShouldPublishToLatest()
```
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: @brthor is there a conditionaltargetattribute we could use with this?

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 4]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
...
+        {
+             Dictionary<string, bool> runtimes = new Dictionary<string, bool>()
```
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: It's not too clear that this code is checking that we have runtime packages for each of these rids, maybe make the function name more descriptive?

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 1 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 2 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 5]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
...
+             {
+                 {"win7-x64", false },
+                 {"win7-x86", false },
+                 {"osx.10.10", false },
+                 {"rhel.7", false },
+                 {"ubuntu.14.04", false },
```
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: CentOS and Debian are missing here.

File: scripts/dotnet-cli-build/Publishing/AzurePublisher.cs [hunk 6]
```diff
@@ -36,23 +37,13 @@ private CloudBlobContainer GetDotnetBlobContainer(string connectionString)
...
             var installerFileBlob = CalculateInstallerBlob(installerFile, channel, version);
-
-            var latestInstallerFileName = installerFile.Replace(version, "latest");
-            var latestInstallerFileBlob = CalculateInstallerBlob(latestInstallerFileName, channel, "Latest");
-
             PublishFile(installerFileBlob, installerFile);
-            PublishFile(latestInstallerFileBlob, installerFile);
         }
 
         public void PublishArchiveAndLatest(string archiveFile, string channel, string version)
```
Comment (brthor) [inline scripts/dotnet-cli-build/Publishing/AzurePublisher.cs]: Change to PublishArchive?

File: scripts/dotnet-cli-build/Publishing/AzurePublisher.cs [hunk 7]
```diff
@@ -36,23 +37,13 @@ private CloudBlobContainer GetDotnetBlobContainer(string connectionString)
         public void PublishInstallerFileAndLatest(string installerFile, string channel, string version)
```
Comment (brthor) [inline scripts/dotnet-cli-build/Publishing/AzurePublisher.cs]: Change to PublishInstaller?

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 4 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: How's ```CheckIfAllRidsHavePublished```?

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 8]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
         [Environment("PUBLISH_TO_AZURE_BLOB", "1", "true")] // This is set by CI systems
         public static BuildTargetResult Publish(BuildTargetContext c)
         {
+            if (ShouldPublishToLatest())
```
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: If this fails, what action should we take? Is the idea that for the last build running this will be true?

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 9]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
...
+            _latestBlobs = new List<string>(AzurePublisherTool.ListBlobs($"{Channel}/Binaries/{CliNuGetVersion}/"));
+
+            foreach (string file in _latestBlobs)
+            {
+                string name = Path.GetFileName(file);
+                string key = string.Empty;
+
+                foreach (string runtime in runtimes.Keys)
+                {
+                    if (name.StartsWith($"runtime.{runtime}"))
```
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: This says that `any` artifact for that runtime will do, right? Can we be more specific? I believe that the version badges are the last artifacts we produce. Can we ensure these are version badge files?

**Comment by brthor** [comment]
Have some stylistic/readability comments but overall looks good, nice!

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 3 above)
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Unfortunately you can't pass delegates in the constructor of the attribute. 

So you'd have to create a custom attribute subclassing TargetConditionAttribute and basically calling this function for `EvaluateCondition`

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 4 above)
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: I like it

Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: We need a method for folks to know to add to this dictionary. Can you add a target that will break the build IIF this is an official build AND the RID of the current build is not in this list?

File: scripts/dotnet-cli-build/Publishing/AzurePublisher.cs (hunk 6 above)
Comment (sokket) [inline scripts/dotnet-cli-build/Publishing/AzurePublisher.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 8 above)
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Last build running will be true.

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 5 above)
Comment (eerhardt) [inline scripts/dotnet-cli-build/PublishTargets.cs]: is debian needed here?

Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 10]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
...
+                    {
+                        key = runtime;
+                        break;
+                    }
+                }
+
+                runtimes[key] = true;
```
Comment (eerhardt) [inline scripts/dotnet-cli-build/PublishTargets.cs]: seems like we should check for !string.IsNullOrEmpty(key)

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 11]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
...
+            }
+
+            foreach (string key in runtimes.Keys)
```
Comment (eerhardt) [inline scripts/dotnet-cli-build/PublishTargets.cs]: can be simplified:

return runtimes.Keys.All(key => runtimes[key]);

**Comment by eerhardt** [comment]
:-1:

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 9 above)
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: per offline conversation, let's add a "FinalizeBuildPublishing" target that in turn calls the "PublishVersionBadge" Target. This will show in code that PublishVersion is a Finalization step.

Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Once that is done, the check here should validate that the version badge exists.

Comment (Sridhar-MS) [inline scripts/dotnet-cli-build/PublishTargets.cs]: yup. Version badge is the right artifact to use here

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 12]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
         [Environment("PUBLISH_TO_AZURE_BLOB", "1", "true")] // This is set by CI systems
         public static BuildTargetResult Publish(BuildTargetContext c)
         {
```
Comment (Sridhar-MS) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Lets not piggy back on the `Publish` target. This should be its own target `PublishLatestArtifacts`.

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 13]
```diff
@@ -45,15 +49,63 @@ public static BuildTargetResult InitPublish(BuildTargetContext c)
...
+            if (ShouldPublishToLatest())
+            {
+                string targetContainer = $"{Channel}/Binaries/Latest/";
+
+                foreach (string blob in _latestBlobs)
+                    AzurePublisherTool.CopyBlob(blob.Replace("/dotnet/", ""), (targetContainer + Path.GetFileName(blob)).Replace(CliNuGetVersion, "latest").Replace(SharedFrameworkNugetVersion, "latest"));
+
+                PublishLatestCliVersionTextFile(c);
+                PublishLatestSharedFrameworkVersionTextFile(c);
```
Comment (Sridhar-MS) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Does this mean we are going to publish the latest version text file only for the current RID?

File: scripts/dotnet-cli-build/Publishing/AzurePublisher.cs (hunk 7 above)
Comment (sokket) [inline scripts/dotnet-cli-build/Publishing/AzurePublisher.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 8 above)
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: If the last two builds run the publish step at the same time, seems like this will break down.

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 13 above)
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: This is a good point, shouldn't we need it for all the supported rids?

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 9 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed to look for the badge

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 10 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Good catch, fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 11 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Nice! Thanks, fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 12 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 4 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: The ```CheckIfAllBuildsHavePublished``` function will do this check since that's where the dictionary lives; it makes sense to have the exception thrown from as-close-as-possible to where the error is.

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 8 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Added taking a lease on the blob container to prevent this

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 13 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 14]
```diff
@@ -48,12 +52,111 @@ public static BuildTargetResult Publish(BuildTargetContext c)
             return c.Success();
         }
 
+        [Target]
+        public static BuildTargetResult FinalizeBuild(BuildTargetContext c)
```
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Might be missing it, but how does this get executed, what target has a dependency on it?

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 15]
```diff
@@ -48,12 +52,111 @@ public static BuildTargetResult Publish(BuildTargetContext c)
...
+                    {
+                        string targetUrl = $"{targetContainer}{Path.GetFileName(blob)}"
+                                        .Replace(CliNuGetVersion, "latest")
+                                        .Replace(SharedFrameworkNugetVersion, "latest");
+                        AzurePublisherTool.CopyBlob(blob.Replace("/dotnet/", ""), targetUrl);
+                    }
+
+                    // Copy the DNVM latest version files and delete the temp files
+                    IEnumerable<string> dnvmBlobs = AzurePublisherTool.ListBlobs($"{Channel}/dnvm/temp/");
+                    foreach (string blob in dnvmBlobs)
```
Comment (Sridhar-MS) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Instead we can just publish the latest version text files for all OSes from the current OS. Makes it much simpler.

**Comment by piotrpMSFT** [comment]
@sokket did you send approval mail?

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 16]
```diff
@@ -48,12 +52,111 @@ public static BuildTargetResult Publish(BuildTargetContext c)
...
+                 { "RHEL_x64", false },
+                 { "OSX_x64", false },
+                 { "Debian_x64", false },
+                 { "CentOS_x64", false }
+             };
+
+            _latestBlobs = new List<string>(AzurePublisherTool.ListBlobs($"{Channel}/Binaries/{CliNuGetVersion}/"));
+
+            var config = Environment.GetEnvironmentVariable("CONFIGURATION");
+            var versionBadgeName = $"{CurrentPlatform.Current}_{CurrentArchitecture.Current}";
```
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Are we sure we don't want the Current.CurrentPlatform.Current.Current? haha, we need to fix that up at some point.

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 17]
```diff
@@ -48,12 +52,111 @@ public static BuildTargetResult Publish(BuildTargetContext c)
...
+            if (badges.ContainsKey(versionBadgeName) == false)
+                throw new ArgumentException("A new OS build was added without adding the moniker to the {nameof(badges)} lookup");
```
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: {

}

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 18]
```diff
@@ -48,12 +52,111 @@ public static BuildTargetResult Publish(BuildTargetContext c)
...
+                 { "OSX_x64", false },
+                 { "Debian_x64", false },
+                 { "CentOS_x64", false }
+             };
+
+            _latestBlobs = new List<string>(AzurePublisherTool.ListBlobs($"{Channel}/Binaries/{CliNuGetVersion}/"));
+
+            var config = Environment.GetEnvironmentVariable("CONFIGURATION");
+            var versionBadgeName = $"{CurrentPlatform.Current}_{CurrentArchitecture.Current}";
+            if (badges.ContainsKey(versionBadgeName) == false)
```
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: {

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 19]
```diff
@@ -48,12 +52,111 @@ public static BuildTargetResult Publish(BuildTargetContext c)
...
+                string targetContainer = $"{Channel}/Binaries/Latest/";
+                string targetVersionFile = $"{targetContainer}{CliNuGetVersion}";
+                string leaseId = AzurePublisherTool.AcquireLeaseOnContainer();
+
+                // Prevent race conditions by dropping a version hint of what version this is. If we see this file
+                // and it is the same as our version then we know that a race happened where two+ builds finished 
+                // at the same time and someone already took care of publishing and we have no work to do.
+                if (AzurePublisherTool.IsLatestSpecifiedVersion(targetVersionFile))
+                {
+                    AzurePublisherTool.ReleaseLeaseOnContainer(leaseId);
```
Comment (piotrpMSFT) [inline scripts/dotnet-cli-build/PublishTargets.cs]: I guess the scenario here is that:
build 1> grabbed lease
build 1> wrote version file
azure> expired lease
build 2> got lease

?

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 14 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 15 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 17 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 18 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 19 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Close, the flow is as such (changed slightly between version of my PR):

1) try acquire a lease on the ```latest``` folder
2) Write version and do work
3) Release lease

If there is contention, the second build will wait and then see the version file once the lease expires and exit quickly. The only coordination object is the latest folder itself

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 16 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: 👍

File: scripts/dotnet-cli-build/CompileTargets.cs [hunk 20]
```diff
@@ -645,11 +640,6 @@ private static BuildTargetResult CompileCliSdk(BuildTargetContext c, DotNetCli d
 
             CrossgenUtil.CrossgenDirectory(c, outputDir);
 
-            // Generate .version file
-            var version = buildVersion.NuGetVersion;
-            var content = $@"{c.BuildContext["CommitHash"]}{Environment.NewLine}{version}{Environment.NewLine}";
-            File.WriteAllText(Path.Combine(outputDir, ".version"), content);
```
Comment (eerhardt) [inline scripts/dotnet-cli-build/CompileTargets.cs]: Does this mean that the SDK directory won't contain a .version file any more?  We have code that depends on that - specifically: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/DotnetFiles.cs#L16

Comment (sokket) [inline scripts/dotnet-cli-build/CompileTargets.cs]: No, the /dnvm directory will still contain version files; they are just populated all at once at the end now

**Comment by sokket** [comment]
@dotnet-bot test this please

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 16 above)
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: @Sridhar-MS and I thought about this before and came away blank 😄 agreed the name is weird

RuntimePlatform.Current maybe

File: scripts/dotnet-cli-build/CompileTargets.cs (hunk 20 above)
Comment (eerhardt) [inline scripts/dotnet-cli-build/CompileTargets.cs]: I mean the .version file being laid down on disk by the installer/tarball/.zip.  Not a version file that is being uploaded to azure.

Comment (sokket) [inline scripts/dotnet-cli-build/CompileTargets.cs]: Fixed

File: scripts/dotnet-cli-build/PublishTargets.cs [hunk 21]
```diff
@@ -24,6 +26,8 @@ public static class PublishTargets
 
         private static string SharedFrameworkNugetVersion { get; set; }
 
+        private static List<string> _latestBlobs;
```
Comment (eerhardt) [inline scripts/dotnet-cli-build/PublishTargets.cs]: I think the general approach is to put properties into the BuildTargetContext instead of having static variables.

But looking deeper - it looks like you can just return the List<string> as an out parameter of `CheckIfAllBuildsHavePublished` and remove this static variable.

**Comment by sokket** [comment]
Any further comments / feedback? :)

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 21 above)
Comment (sokket) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Peter and I talked about that offline and we ended up with the static variable being a little more clear than an out var. I'm open to re-opening that discussion if you want :)

Comment (eerhardt) [inline scripts/dotnet-cli-build/PublishTargets.cs]: No, no reason to re-open.

Looking again, it should be "s_" prefixed to follow the coding style here https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

**Comment by eerhardt** [comment]
:shipit:

**Comment by Sridhar-MS** [comment]
:shipit: Lets keep an eye on the builds after merging.

File: scripts/dotnet-cli-build/PublishTargets.cs (hunk 21 above)
Comment (brthor) [inline scripts/dotnet-cli-build/PublishTargets.cs]: Happy that we are moving away from `BuildTargetContext` 👍 It's Hard to keep track of variables as strings

**Comment by weshaggard** [comment]
Is there any reason you aren't also publishing the nuget packages for the host and meta-package as part of this finalize step? The only interesting aspect I can see is that you are essentially doing this Azure publish to Latest form whichever leg finishes last and if that leg is non-windows I don't think we have any great tools to publish the packages. 

My concern here though is that we will still be in a broken state between the time the Latest in blob storage gets updated and when the meta-package gets published.

**Comment by eerhardt** [comment]
NuGet xplat does support Push:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PushCommand.cs

We could use that from our build scripts by referencing that package.
