### PR TITLE
Map solution configurations to existing project configurations on add. 

### LINKED ISSUE #6221: Visual Studio modifies solution files created from the dotnet CLI.
## Steps to reproduce
```
mkdir test
cd test
dotnet new sln
dotnet new console -o console
dotnet sln add .\console\console.csproj
# commit to git repo before opening in VS
```
open the solution with Visual Studio (version info below), open diff of test.sln: 
image

## Expected  behavior
I would assume Visual Studio would leave the file alone. Or, the template from `dotnet new sln` should conform with what Visual Studio expects. 

## Actual behavior
Visual Studio makes many changes, see above. 

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

## System info:
image

## Visual Studio info:
Microsoft Visual Studio Community 2017
Version 15.0.26228.12 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

### PR DESCRIPTION
**Pull request by peterhuene**
This PR implements solution configuration to project configuration mapping.

Previously, when a project was added to the solution with the `sln add`
command, solution configurations would be mapped to a project configuration and
platform of the same name, regardless of whether or not the project had a
configuration or platform of that name.  This caused the solution to appear
dirty when opened in Visual Studio if the configuration or platform did not
exist at the project level because Visual Studio would attempt to correct the
mapping.

The fix is to check what configurations and platforms are supported by the
project and only map to what is present.  If a solution configuration can't be
mapped, the first configuration/platform supported by the project is chosen;
this is consistent with how Visual Studio does the fallback mapping.

Fixes #6221.

### CODE REVIEW

File: src/dotnet/ProjectInstanceExtensions.cs [hunk 1]
```diff
@@ -45,5 +46,25 @@ public static string GetProjectTypeGuid(this ProjectInstance projectInstance)
 
             return projectTypeGuid;
         }
+
+        public static IEnumerable<string> GetPlatforms(this ProjectInstance projectInstance)
+        {
+            return (projectInstance.GetPropertyValue("Platforms") ?? "AnyCPU")
```
[the remark this answers is not in the document]
Comment (peterhuene) [reply src/dotnet/ProjectInstanceExtensions.cs]: I'll remove the duplication.

File: test/dotnet-sln-add.Tests/GivenDotnetSlnAdd.cs [hunk 2]
```diff
@@ -788,6 +853,32 @@ private void WhenSlnContainsSolutionFolderWithDifferentCasingItDoesNotCreateDupl
...
+                .ExecuteWithCapturedOutput($"sln add App");
+            result.Should().Pass();
+
+            result = new DotnetCommand()
+                .WithWorkingDirectory(slnDirectory)
+                .ExecuteWithCapturedOutput($"sln add Lib");
+            result.Should().Pass();
+
+            File.ReadAllText(slnFullPath)
+                .Should().BeVisuallyEquivalentTo(ExpectedSlnFileAfterAddingProjectsWithPlatformsAndConfigs);
```
Comment (wli3) [inline test/dotnet-sln-add.Tests/GivenDotnetSlnAdd.cs]: nit pick: This tests is too "integration". As a result, it is hard to understand what is changed, what is the "important" part you want to assert from the test.  For example, is "VisualStudioVersion = 15.0.26006.2" important?

Also, this test will be easy to break due to unrelated change, like VisualStudioVersion move to 16

Comment (peterhuene) [reply test/dotnet-sln-add.Tests/GivenDotnetSlnAdd.cs]: Great feedback, thanks.  It does test two things at once, which is that App should have the configurations all mapped to "AnyCPU" because it is the only platform it supports while Lib should map to all three supported platforms; simultaneously ignoring configurations/platforms not present at the solution level.  I can break this down into discrete tests.

Comment (peterhuene) [reply test/dotnet-sln-add.Tests/GivenDotnetSlnAdd.cs]: With regards to being fragile due to version numbers in the solution file, the existing tests also appear to suffer from this.  Additionally, it would only be an issue if `sln add` modified the solution version when writing out the modified solution file; as far as I know, it doesn't even look at the version numbers.

File: src/dotnet/SlnFileExtensions.cs [hunk 3]
```diff
@@ -87,57 +98,96 @@ public static void AddDefaultBuildConfigurations(this SlnFile slnFile, SlnProjec
...
-                    projectConfigs[activeCfgKey] = config;
+                    defaultProjectPlatform = projectPlatform;
                 }
 
-                var build0Key = $"{config}.Build.0";
-                if (!projectConfigs.ContainsKey(build0Key))
+                projectPlatforms[projectPlatform] = projectPlatform;
+            }
+
+            foreach (var key in slnFile.SolutionConfigurationsSection.Keys)
```
Comment (livarcocc) [inline src/dotnet/SlnFileExtensions.cs]: It feels to me like this whole foreach couple benefit from having its own method to make it easier to understand what it is doing.

Maybe even move the other pieces into submethods as well to make the algorithm clear here.

Comment (peterhuene) [reply src/dotnet/SlnFileExtensions.cs]: I'll refactor to make the intention clearer.

**Comment by peterhuene** [comment]
@livarcocc I've refactored the mapping code; hopefully the intentions are now clearer.

@wli3 I've broken the one test into three different ones; they still follow the same conventions as the other `sln add` tests, namely comparing the post-operation solution content to a hardcoded baseline content.
