### PR TITLE
Fix Using Command.Create from a Desktop Application

### LINKED ISSUE #2566: Commands cannot execute from a desktop .NET process
## Steps to reproduce
Create a command using Microsoft.DotNet.Cli.Utils.
Call Command.Execute()
Example:
```c#
Command.CreateDotNet(
                "build",
                new[] { projectPath })
                .Execute();
```
## Expected  behavior
Starts process "dotnet.exe build {projectPath}". 
Process begins to execute successfully.
Process can forward stderr/stdout

## Actual behavior
```
Running dotnet.exe build ..\DesktopStartup
System.InvalidOperationException: The Process object must have the UseShellExecute property set to false in order to redirect IO streams.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
```

## Environment data
Microsoft.DotNet.Cli.Utils/1.0.0-rc2-002416

```
Product Information:
 Version:     1.0.0-rc2-002416
 Commit Sha:  37f00f24e9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

This is blocking https://github.com/aspnet/EntityFramework/issues/4577

### PR DESCRIPTION
**Pull request by brthor**
Fixes #2566 

UseShellExecute is true by default on desktop, and false by default on CoreClr

cc @natemcmaster

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2580)

### CODE REVIEW

**Comment by natemcmaster** [comment]
Thanks! :shipit:

**Comment by brthor** [comment]
@eerhardt @Sridhar-MS Please take a quick look over this PR, minor changes to testtargets in build

File: TestAssets/TestProjects/TestAppSimple/Program.cs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+﻿using System;
```
Comment (eerhardt) [inline TestAssets/TestProjects/TestAppSimple/Program.cs]: Don't we already have one of these?

File: TestAssets/TestProjects/TestAppSimple/project.json [hunk 2]
```diff
@@ -0,0 +1,12 @@
+{
+  "version": "1.0.0-*",
+  "compilationOptions": {
+    "emitEntryPoint": true
+  },
+  "dependencies": {
+    "Microsoft.NETCore.App": "1.0.0-rc2-*"
```
Comment (eerhardt) [inline TestAssets/TestProjects/TestAppSimple/project.json]: Should this be type:platform?

File: TestAssets/TestProjects/TestAppSimple/Program.cs (hunk 1 above)
Comment (brthor) [inline TestAssets/TestProjects/TestAppSimple/Program.cs]: Not that I saw, all other test apps seem to have something additional.

File: test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+                .CreateTestInstance("TestAppSimple")
+                .WithLockFiles();
+                
+            var testProject = Path.Combine(testInstance.TestRoot, "project.json");
+            var testProjectToBuild = Path.Combine(testInstanceToBuild.TestRoot, "project.json");
+
+            new RunCommand(testProject).Execute(testProjectToBuild).Should().Pass();
+        }
+    }
+}
```
Comment (eerhardt) [inline test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs]: Nit: newline.

File: TestAssets/TestProjects/TestAppSimple/project.json (hunk 2 above)
Comment (brthor) [inline TestAssets/TestProjects/TestAppSimple/project.json]: the other test apps are not, why do you think it should be?

File: test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs (hunk 3 above)
Comment (brthor) [inline test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs]: at the end of the file?

File: TestAssets/TestProjects/TestAppSimple/project.json (hunk 2 above)
Comment (eerhardt) [inline TestAssets/TestProjects/TestAppSimple/project.json]: That's what `dotnet new` generates, and it's what makes the app "portable".

Without it and without a "runtimes" section, your app isn't really either of the 2 app models we support: portable or standalone.

File: test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+// Licensed under the MIT license. See LICENSE file in the project root for full license information.
+
+using System;
+using System.Collections.Generic;
+using System.IO;
+using System.Runtime.InteropServices;
+using System.Text;
+using System.Linq;
+using Xunit;
+using Moq;
```
Comment (eerhardt) [inline test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs]: Are all these usings needed?

File: TestAssets/TestProjects/TestAppSimple/Program.cs (hunk 1 above)
Comment (eerhardt) [inline TestAssets/TestProjects/TestAppSimple/Program.cs]: Ya, I guess not.  It looks like `TestAssets\TestProjects\PortableTests\PortableApp` is the closest, but it has a bunch of  'runtimeOptions' in its project.json for some reason.

File: TestAssets/TestProjects/TestAppSimple/project.json (hunk 2 above)
Comment (brthor) [inline TestAssets/TestProjects/TestAppSimple/project.json]: I would argue that it is still standalone, albeit requiring an inferred runtime.

File: test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs (hunk 3 above)
Comment (eerhardt) [inline test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs]: Yes, GitHub likes to complain about minor things like that.

**Comment by eerhardt** [comment]
LGTM.

File: test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs (hunk 4 above)
Comment (brthor) [inline test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs]: almost definitely not 😄

**Comment by brthor** [comment]
Thanks for the review @eerhardt

File: test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs (hunk 3 above)
Comment (brthor) [inline test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs]: will change

File: TestAssets/TestProjects/TestAppSimple/project.json (hunk 2 above)
Comment (eerhardt) [inline TestAssets/TestProjects/TestAppSimple/project.json]: Correct - you're adding another dependency on `--infer-runtimes` here, which is supposedly going away at some point...

File: TestAssets/TestProjects/TestAppSimple/Program.cs (hunk 1 above)
Comment (brthor) [inline TestAssets/TestProjects/TestAppSimple/Program.cs]: Yeah at some point we need to bring those PortableTests into the main directory, now that everything is portable/standalone

File: TestAssets/TestProjects/TestAppSimple/project.json (hunk 2 above)
Comment (brthor) [inline TestAssets/TestProjects/TestAppSimple/project.json]: Good point, I will add rids.

I don't want to do type: platform only because I think there's cases where we want a runnable build output (without dotnet run). Feel free to disagree though.

Comment (eerhardt) [inline TestAssets/TestProjects/TestAppSimple/project.json]: We need a mix, right?  We need some portable test assets and some standalone test assets.

File: test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs (hunk 3 above)
Comment (brthor) [inline test/Microsoft.DotNet.Cli.Utils.Tests/GivenADesktopAppWhichUsesCommandCreateDotnet.cs]: added

File: TestAssets/TestProjects/TestAppSimple/project.json (hunk 2 above)
Comment (brthor) [inline TestAssets/TestProjects/TestAppSimple/project.json]: Yup, but what do we say is the default case or do we make two of each test app?
