### PR TITLE
Fix Razor server shutdown on Windows.

### LINKED ISSUE #9158: Build-server shutdown doesn't get credentials to delete Razor PID file
## Steps to reproduce
Install latest RC CLI build
In powershell or cmd prompt, run the following:
dotnet new razor
dotnet build
dotnet build-server shutdown

## Expected  behavior
The Razor build server is shutdown and the PID file is deleted

## Actual behavior
Exception is thrown:

PS C:\Users\v-masche\servertests\test3> dotnet build-server shutdown
Shutting down MSBuild server...
Shutting down VB/C# compiler server...
System.IO.IOException: The process cannot access the file 'C:\Users\v-masche\.dotnet\pids\build\rzc-8784' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.OpenRead(String path)
   at Microsoft.DotNet.BuildServer.RazorPidFile.Read(FilePath path, IFileSystem fileSystem)
   at Microsoft.DotNet.BuildServer.BuildServerProvider.EnumerateBuildServers(ServerEnumerationFlags flags)+MoveNext()
   at Microsoft.DotNet.Tools.BuildServer.Shutdown.BuildServerShutdownCommand.StartShutdown()
   at Microsoft.DotNet.Tools.BuildServer.Shutdown.BuildServerShutdownCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.BuildServer.BuildServerCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Environment data
`dotnet --info` output:
PS C:\Users\v-masche> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008669
 Commit:    4db4d9b568

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008669\

Host (useful for support):
  Version: 2.1.0-rc1-26425-06
  Commit:  b50a96ee38

.NET Core SDKs installed:
  2.1.300-rc1-008669 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-30676 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-30676 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1-26425-06 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

### PR DESCRIPTION
**Pull request by peterhuene**
On Windows, the Razor server correctly creates the pid file with
`FileAccess.Write` and `FileOptions.DeleteOnClose`.  This requires a share mode
of `FileShare.Write | FileShare.Delete` to open.  However, the
`dotnet build-server shutdown` command was opening the file with
`FileShare.Read`.  As a result, an `IOException` was being thrown and was not
handled.

This change first opens the file with the appropriate share access and also
properly handles a failure to access or read the contents of the pid file.

Additionally, an integration test was added to test that Razor server shutdown
works as expected.

Fixes #9158.

### CODE REVIEW

**Comment by MattGertz** [comment]
OK to take to .NET Core Shiproom.

File: src/dotnet/BuildServer/RazorPidFile.cs [hunk 1]
```diff
@@ -33,32 +33,46 @@ public static RazorPidFile Read(FilePath path, IFileSystem fileSystem = null)
...
+                        return null;
+                    }
 
-                return new RazorPidFile(path, processId, new FilePath(serverPath), pipeName);
+                    return new RazorPidFile(path, processId, new FilePath(serverPath), pipeName);
+                }
+            }
+            catch (Exception ex) when (ex is IOException || ex is UnauthorizedAccessException)
+            {
+                // Any failure to read the file will ignore the file
```
Comment (peterhuene) [inline src/dotnet/BuildServer/RazorPidFile.cs]: I think maybe the `BuildServerProvider` should be given an `IReporter` it can use to report a warning if it failed to open a pid file?  I don't like silent failures.

Comment (peterhuene) [reply src/dotnet/BuildServer/RazorPidFile.cs]: I've decided I'm going to change this and add a test that fails simulates a failure here.

**Comment by peterhuene** [comment]
It looks like the integration test potentially interfered with another CI process that was running a Razor server.  I'm going to have to think about how to isolate this or disable the test.

File: test/dotnet.Tests/CommandTests/BuildServerShutdownCommandTests.cs [hunk 2]
```diff
@@ -157,6 +160,32 @@ public void GivenAFailingShutdownItPrintsFailureMessage()
...
+                .WithWorkingDirectory(testInstance.Root)
+                .ExecuteWithCapturedOutput("shutdown --razor")
+                .Should()
+                .Pass()
+                .And
+                .HaveStdOutMatching(
+                    string.Format(
+                        LocalizableStrings.ShutDownSucceededWithPid,
+                        CommandLocalizableStrings.RazorServer,
+                        @"\d+").Replace("(", @"\(").Replace(")", @"\)"));
```
Comment (wli3) [inline test/dotnet.Tests/CommandTests/BuildServerShutdownCommandTests.cs]: nit:what is this? looks flaky

Comment (peterhuene) [reply test/dotnet.Tests/CommandTests/BuildServerShutdownCommandTests.cs]: The message contains `(process ####)`, so this turns that part into `\(\d+\)` to match a regex.

This is being removed anyway with my next push to ensure this test properly isolates the running Razor server (both with the pipe name it uses and the pid directory it creates the pid file in).

Comment (peterhuene) [reply test/dotnet.Tests/CommandTests/BuildServerShutdownCommandTests.cs]: I've pushed up that change.

**Comment by peterhuene** [comment]
Okay, pushed up a fix for the integration test.  The Razor server now uses a unique pipe name and pid file directory, which should effectively isolate it from any other CI process.
