### PR TITLE
abort build when an unresolved dependency is found

### LINKED ISSUE #2695: Errors are unclear when a project has an unresolved dependency
## Steps to reproduce
1. `dotnet new`
2. Add a dependency on a project that does not exist, for example:

```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002498"
    },
    "ThisIsNotARealDependencyAndIfSomeoneGoesAndAddsAProjectWithThisNameIWillFindThemAndPunishThem": { "target": "project" }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```
3. `dotnet restore` (this should fail but write a lock file)
4. `dotnet build`

## Expected  behavior
A helpful error message

## Actual behavior
Outputs

```
Unable to cast object of type 'Microsoft.DotNet.ProjectModel.LibraryDescription' to type 'Microsoft.DotNet.ProjectModel.ProjectDescription'.
```

Also, if this error is bypassed, you get even worse behavior. It emits an error for the unresolved dependency, but continues the build and as long as you don't use the code it actually produces a binary. This leads to weird behavior where you try again and it says it doesn't have to compile because the outputs are up-to-date.

## Environment data
`dotnet --info` output:

```
ps1 # dotnet --info
.NET Command Line Tools (1.0.0-rc2-002498)

Product Information:
 Version:     1.0.0-rc2-002498
 Commit Sha:  55e561bfb3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14329
 OS Platform: Windows
 RID:         win10-x64
```

### PR DESCRIPTION
**Pull request by anurse**
Fixes #2695 

/cc @pakrym @davidfowl

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2696)

### CODE REVIEW

**Comment by pakrym** [comment]
:shipit:

**Comment by anurse** [comment]
@dotnet-bot test this please

File: src/dotnet/commands/dotnet-compile/ManagedCompiler.cs [hunk 1]
```diff
@@ -63,11 +63,10 @@ public override bool Compile(ProjectContext context, BuildCommandApp args)
                 diagnostics.Add(diag);
             }
 
-            if (missingFrameworkDiagnostics.Count > 0)
+            if(diagnostics.Any(d => d.Severity == DiagnosticMessageSeverity.Error))
```
Comment (davidfowl) [inline src/dotnet/commands/dotnet-compile/ManagedCompiler.cs]: nit: spacing

**Comment by davidfowl** [comment]
Good change :shipit:

File: src/dotnet/commands/dotnet-build/ProjectGraphCollector.cs [hunk 2]
```diff
@@ -44,7 +44,7 @@ private ProjectGraphNode TraverseProject(ProjectDescription project, IDictionary
                     LibraryDescription libraryDescription;
                     if (lookup.TryGetValue(dependency.Name, out libraryDescription))
                     {
-                        if (libraryDescription.Identity.Type.Equals(LibraryType.Project))
+                        if (libraryDescription.Resolved && libraryDescription.Identity.Type.Equals(LibraryType.Project))
```
Comment (cdmihai) [inline src/dotnet/commands/dotnet-build/ProjectGraphCollector.cs]: Shouldn't it be an error if the project is not resolved?

Right now, if a project is not resolved the else branch is taken which implicitly assumes that it receives a non ProjectDescription. This might lead to a wrong graph.

Comment (anurse) [inline src/dotnet/commands/dotnet-build/ProjectGraphCollector.cs]: It is an error and it will be caught later. This was causing an InvalidCastException.

Before compiling, we do check if all libraries are resolved.

Comment (anurse) [inline src/dotnet/commands/dotnet-build/ProjectGraphCollector.cs]: And, an unresolved project library will not have any dependencies (since we couldn't find the project file) so even the else clause will no-op.
