### PR TITLE
fix framework assembly resolution for net35

### LINKED ISSUE #2525: Issues dotnet build when targeting net35 with frameworkAssemblies
## Steps to reproduce
Create a library targeting net35 where you include frameworkAssemblies

## Expected  behavior
Builds correctly providing you setup everything correctly

## Actual behavior
Errors out with lots of 
'Predefined type 'System.Void' is not defined or imported'
etc...

I believe the issue to be that when dynamically creating the dotnet-compile-csc.rsp and dotnet-compile.rsp

When targeting net40 or net45 
with similar dependencies they include 
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\...System.Data.dll"

Net35 was not, on manually adding the required references i could successfully build the package.
these were my references
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\mscorlib.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.Core.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.Data.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.configuration.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.XML.dll"

### PR DESCRIPTION
**Pull request by anurse**
Fixes #2525 

Turns out in System.Version land `3.5.0.0` is **not** less than or equal to `3.5`.

/cc @davidfowl @pakrym

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2557)

### CODE REVIEW

File: TestAssets/TestProjects/TestLibraryWithMultipleFrameworks/Program.cs [hunk 1]
```diff
@@ -7,6 +8,10 @@ public class Program
         public static void Main()
         {
             Console.WriteLine("Hello World!");
+#if !NETSTANDARDAPP1_5
```
Comment (Petermarcu) [inline TestAssets/TestProjects/TestLibraryWithMultipleFrameworks/Program.cs]: Is this going to bite us as we go to 1.6? Is this really just for 3.5? Can we condition on that?

Comment (anurse) [inline TestAssets/TestProjects/TestLibraryWithMultipleFrameworks/Program.cs]: This is only in a test, but yes it would be affected by a change to 1.6. However, it would be the smallest of a whole host of things that would be affected :).

I can change it to `NET20 || NET35 || NET40 || ...` which will be slightly more stable.

**Comment by brthor** [comment]
👀 
We're going to conflict so want to see when this goes in.

**Comment by anurse** [comment]
Ping @davidfowl / @pakrym for review

**Comment by pakrym** [comment]
:shipit:
