### PR TITLE
Expand relative paths for CLI arguments

### LINKED ISSUE #6700: Dotnet publish output parameter doesn't work
## Steps to reproduce
```
C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox [master +2 ~5 -0 !]> dotnet publish .\Sandbox.sln -c Release -o .\output\
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\docker-compose.dcproj : error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.Docker.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
  Sandbox.Web -> C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Web\bin\Release\netcoreapp1.1\Sandbox.Web.dll
  Sandbox.Api -> C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Api\bin\Release\netcoreapp1.1\Sandbox.Api.dll
C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox [master +2 ~5 -0 !]> ls -l .\output\
```

Files are available in `C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Api\bin\Release\netcoreapp1.1` and `C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Web\bin\Release\netcoreapp1.1`, which is not what I need. `output` folder remains empty.

## Expected  behavior
Compiled dlls in output folder, in the above example in `.\output`. I would expect dlls in output folder as specified by output argument.

## Actual behavior
There is no actual difference running with or without -o parameter.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

I get the same behavior in container from image `aspnetcore:1.1.2-jessie`.

### PR DESCRIPTION
**Pull request by dasMulli**
Continuation of https://github.com/dotnet/cli/pull/7166 which was too late for 2.0

This changes the output directory for CLI commands to be expanded to a full path based on the current working directory.

This may be a breaking change for some users.

Fixes #6700, #4765

### CODE REVIEW

**Comment by wli3** [comment]
I like it. My concern is we don't have a good way to prevent people forgetting to use full path in the future. But it should be an improvement anyway.

Put that in master is appropriate. I am not confident there is no unexpected bug since we have existing mixed path, so it could get move testing. @dotnet/cli-contrib what do you think?

**Comment by dasMulli** [comment]
I still left it `WIP` because I wanted to do a few more manual passes on at least win/Mac on some of the arguments to be certain all the modifications work.
Feedback is highly appreciated.

File: src/dotnet/CommandDirectoryContext.cs [hunk 1]
```diff
@@ -0,0 +1,46 @@
+﻿using System;
+using System.IO;
+
+namespace Microsoft.DotNet.Cli
+{
+    internal static class CommandDirectoryContext
```
Comment (peterhuene) [inline src/dotnet/CommandDirectoryContext.cs]: There exists an overload of `Path.GetFullPath` that [takes a base](https://github.com/dotnet/coreclr/pull/15579) other than CWD, if desired.  Could that be leveraged instead of this type?

Comment (dasMulli) [reply src/dotnet/CommandDirectoryContext.cs]: Hah that one is so new I didn't know about it 😂 
I'll change it.

**Comment by dasMulli** [comment]
test Debian8.2 x64 Debug Build 
test Linux_NoSuffix x64 Release Build

**Comment by dasMulli** [comment]
test Ubuntu x64 Release Build
test Linux_NoSuffix x64 Release Build

**Comment by dasMulli** [comment]
@peterhuene could you take another look?

File: src/dotnet/CommandDirectoryContext.cs [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+        private static string _currentDirectoryOverwrite;
+
+        /// <summary>
+        /// Expands a path similar to Path.GetFullPath() but allows unit tests a hook to inject an overwrite to the
+        /// current working directory.
+        /// </summary>
+        /// <param name="path">A realtive or absolute path specifier</param>
+        /// <returns>The full path to the target</returns>
+        public static string ExpandPath(string path)
+            => _currentDirectoryOverwrite is string basePath
```
Comment (peterhuene) [inline src/dotnet/CommandDirectoryContext.cs]: Is the cast here necessary rather than a null check?

File: src/dotnet/CommandDirectoryContext.cs [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+        [ThreadStatic]
+        private static string _currentDirectoryOverwrite;
+
+        /// <summary>
+        /// Expands a path similar to Path.GetFullPath() but allows unit tests a hook to inject an overwrite to the
+        /// current working directory.
+        /// </summary>
+        /// <param name="path">A realtive or absolute path specifier</param>
+        /// <returns>The full path to the target</returns>
+        public static string ExpandPath(string path)
```
Comment (peterhuene) [inline src/dotnet/CommandDirectoryContext.cs]: Nit: I think this should be named `GetFullPath` as well to better convey the fact that this is just `Path.GetFullPath` with a configurable base path.

File: src/dotnet/CommandDirectoryContext.cs [hunk 4]
```diff
@@ -0,0 +1,46 @@
+﻿using System;
+using System.IO;
+
+namespace Microsoft.DotNet.Cli
+{
+    internal static class CommandDirectoryContext
+    {
+        [ThreadStatic]
+        private static string _currentDirectoryOverwrite;
```
Comment (peterhuene) [inline src/dotnet/CommandDirectoryContext.cs]: Nit: can we call this `_basePath` since it isn't related to CWD?

File: src/dotnet/CommandDirectoryContext.cs [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+
+        /// <summary>
+        /// Expands a path similar to Path.GetFullPath() but allows unit tests a hook to inject an overwrite to the
+        /// current working directory.
```
Comment (peterhuene) [inline src/dotnet/CommandDirectoryContext.cs]: Nit: should refer to base path rather than CWD.

File: src/dotnet/CommandDirectoryContext.cs [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+                ? Path.GetFullPath(path, basePath)
+                : Path.GetFullPath(path);
+
+        /// <summary>
+        /// Meant to be used only in unit test to remove dependency on special characters in the absolute repo path
+        /// The overwrite will only affect the current thread.
+        /// </summary>
+        /// <param name="currentDirectory">Directory to be used instead of the current working directory.</param>
+        /// <param name="action">Action to be executed with the overwritten directory in place.</param>
+        public static void PerformActionWithOverwrittenCurrentDirectory(string currentDirectory, Action action)
```
Comment (peterhuene) [inline src/dotnet/CommandDirectoryContext.cs]: Can we call this `PerformActionWithBasePath` since this doesn't related to CWD, only sets the base path to use for `GetFullPath` calculations?

File: src/dotnet/CommandDirectoryContext.cs (hunk 2 above)
Comment (dasMulli) [reply src/dotnet/CommandDirectoryContext.cs]: I should look at the generated code but wanted to avoid an extra TLS read but since there are no perf considerations I'll do it

File: test/Microsoft.DotNet.Tools.Tests.Utilities/TestPathUtilities.cs [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+
+using System;
+using System.IO;
+using System.Runtime.InteropServices;
+
+namespace Microsoft.DotNet.Tools.Test.Utilities
+{
+    public static class TestPathUtilities
+    {
+        public static string CreateAbsolutePath(string directoryName = null)
```
Comment (peterhuene) [inline test/Microsoft.DotNet.Tools.Tests.Utilities/TestPathUtilities.cs]: The name here makes me think it's going to create the given directory rather than format an absolute path from the given directory name.  Perhaps `FormatAbsolutePath`?

File: src/dotnet/CommandDirectoryContext.cs (hunk 2 above)
Comment (peterhuene) [reply src/dotnet/CommandDirectoryContext.cs]: If the extra read is a concern, then I think this would be better as normal function implementation that declared a local with a small comment explaining why the local is being assigned.

**Comment by peterhuene** [comment]
I'm finished reviewing, mostly nits regarding naming of things.  This looks great!  With the remaining nits dealt with, I think we're ready to merge this.

Ping @livarcocc regarding this PR since it is a breaking change (a good one, imo).  Should we document this behavior for 3.0 release notes somewhere?

**Comment by livarcocc** [comment]
adding @leecow and @KathleenDollard for the breaking change documentation.

**Comment by dasMulli** [comment]
@peterhuene thanks, addressed naming issues. #NamingIsHard

**Comment by peterhuene** [comment]
@livarcocc any objections to merging this into 3.0?

**Comment by leecow** [comment]
Definitely add a "breaking change" label.

**Comment by livarcocc** [comment]
I have marked the bugs and the PR with a breaking change label. I will merge the PR in a couple minutes.

**Comment by livarcocc** [comment]
@dasMulli thank you very much for the contribution,

**Comment by mot256** [comment]
Can you please put this in the "what's new" documentation of .NET Core 3.0? This subtle change actually has a side effect on build servers that build both .NET Core 2.x and .NET Core 3.0 projects with the same build scripts. Although we accept that this is a breaking change (and we will separate the build steps between .NET Core 2 and 3 projects now that we know it), but it just not announce in the release note (at least in what we could find here: https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0)

**Comment by dasMulli** [comment]
cc @mairaw @KathleenDollard  for docs/visibility

**Comment by KathleenDollard** [comment]
Which version did this go out in and what commands does it effect? At this point, is ti a matter for release docs or as a note in relevant docs? Ideas for text welcome.

**Comment by dasMulli** [comment]
I think this went out in .NET Core 3.0 Preview 1 and affects the build, clean, pack, publish, restore, store and test commands.

Ad wording, maybe something like?:
Arguments to `dotnet` commands operating on project files that take paths to files or directory are now interpreted as relative to the current working directory rather than relative to the project file, which was confusing when the project being built was not inside the current working directory.

**Comment by peterhuene** [comment]
@dasMulli is correct, pretty sure this was P1.  I have nothing else to add to the text because I think that sums it up well.

**Comment by mot256** [comment]
What is the expected behavior when a solution is built with this change? Will it append the project name to the path?

**Comment by mohlerm** [comment]
@dasMulli @mairaw @KathleenDollard Will this still be added to the release notes? In our case, this breaks our CI/CD chain so I think it should be visible in the notes.
Cheers
