### PR TITLE
Quote variable expansions in dotnet-install.sh

### LINKED ISSUE #5281: dotnet-install.sh can't install to path containing spaces
Non-blocking bug, but I noticed this when making an upstream shell script handle spaces properly.

## Steps to reproduce
Run `scripts/obtain/dotnet-install.sh --install-dir a\ b\ c`

## Expected  behavior
The .NET CLI is installed into a folder in the current directory called "a b c".

## Actual behavior
The .NET CLI is installed into a folder in the current directory called "a".

Adding `--verbose` shows a step where the path is trimmed:
```
dotnet-install: Calling: resolve_installation_path a b c
dotnet-install: install_root=a
```

## Environment data
OSX bash `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)`
Ubuntu Trusty bash `GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)`

### PR DESCRIPTION
**Pull request by benknoble**
Fix #5281 to prevent paths with spaces from causing problems due to word
splitting.

Some of them aren't likely to have issues, but safety first.

See also dotnet/roslyn#22320 for something similar

### CODE REVIEW

File: scripts/obtain/dotnet-install.sh [hunk 1]
```diff
@@ -534,17 +534,18 @@ get_absolute_path() {
...
+    local root_path="$(remove_trailing_slash "$1")"
+    local out_path="$(remove_trailing_slash "$2")"
+    local override="$3"
+    local override_switch="$(if [ "$override" = false ]; then printf -- "-n"; fi)"
     
     cat | uniq | while read -r file_path; do
-        local path=$(remove_beginning_slash ${file_path#$root_path})
-        local target=$out_path/$path
+        local path="$(remove_beginning_slash "${file_path#$root_path}")"
+        local target="$out_path"/"$path"
```
Comment (johnbeisner) [inline scripts/obtain/dotnet-install.sh]: Why quote each part? Doesn't this work in a way that's expected: local target="$out_path/$path"?

File: scripts/obtain/dotnet-install.sh [hunk 2]
```diff
@@ -534,17 +534,18 @@ get_absolute_path() {
...
         if [ "$override" = true ] || (! ([ -d "$target" ] || [ -e "$target" ])); then
-            mkdir -p $out_path/$(dirname $path)
-            cp -R $override_switch $root_path/$path $target
+            mkdir -p "$out_path"/"$(dirname "$path")"
+            say "cp -R $override_switch $root_path/$path $target"
+            cp -R "$override_switch" "$root_path"/"$path" "$target"
```
Comment (johnbeisner) [inline scripts/obtain/dotnet-install.sh]: This shouldn't be quoted: "$override_switch"

File: scripts/obtain/dotnet-install.sh (hunk 1 above)
Comment (benknoble) [reply scripts/obtain/dotnet-install.sh]: It does--I think I did that because I was searching around for $word patterns and quote-surrounding them. Can definitely be changed.

File: scripts/obtain/dotnet-install.sh (hunk 2 above)
Comment (benknoble) [reply scripts/obtain/dotnet-install.sh]: Yes, discovered that just now

File: scripts/obtain/dotnet-install.sh [hunk 3]
```diff
@@ -765,7 +766,7 @@ do
             override_non_versioned_files=false
             ;;
         -?|--?|-h|--help|-[Hh]elp)
-            script_name="$(basename $0)"
+            script_name="$(basename "$0")"
```
Comment (johnbeisner) [inline scripts/obtain/dotnet-install.sh]: Is this necessary: "$0"? What is the breaking scenario?

File: scripts/obtain/dotnet-install.sh [hunk 4]
```diff
@@ -534,17 +534,18 @@ get_absolute_path() {
...
     eval $invocation
 
-    local root_path=$(remove_trailing_slash $1)
-    local out_path=$(remove_trailing_slash $2)
-    local override=$3
-    local override_switch=$(if [ "$override" = false ]; then printf -- "-n"; fi)
+    local root_path="$(remove_trailing_slash "$1")"
+    local out_path="$(remove_trailing_slash "$2")"
+    local override="$3"
+    local override_switch="$(if [ "$override" = false ]; then printf -- "-n"; fi)"
```
Comment (johnbeisner) [inline scripts/obtain/dotnet-install.sh]: This line looked fine as it was; the resultant "-n" was quoted, I think that's enough...

File: scripts/obtain/dotnet-install.sh (hunk 3 above)
Comment (benknoble) [reply scripts/obtain/dotnet-install.sh]: Hypothetically:
```
$ basename music/imagine dragons
imagine
$ basename "music/imagine dragons"
imagine dragons
$ basename a dir/file
a
$ basename "a dir/file"
file
```

If the script name **never** contains spaces, then there wouldn't be any issues. If the full path to the script **never** contains spaces, then there wouldn't be any issues. The goal was to fix potential space-containing paths breaking scripts.

Comment (johnbeisner) [reply scripts/obtain/dotnet-install.sh]: So it's the path that could potentially contains spaces; okay - good.

File: scripts/obtain/dotnet-install.sh (hunk 4 above)
Comment (benknoble) [reply scripts/obtain/dotnet-install.sh]: I agree, but I figured presenting quoted "$()" as a good style might also be warranted. Would you prefer the quotes here removed?

Comment (johnbeisner) [reply scripts/obtain/dotnet-install.sh]: Yes, please.

File: scripts/obtain/dotnet-install.sh (hunk 1 above)
Comment (johnbeisner) [reply scripts/obtain/dotnet-install.sh]: Yes, please.

**Comment by benknoble** [comment]
@johnbeisner Looks like it passes.

**Comment by johnbeisner** [comment]
@benknoble 
Thank you for your contribution.
