### PR TITLE
Fix dotnet-compile-fsc

### LINKED ISSUE #1199: dotnet build of app+library fail (exception) if library pdb doesnt exists
App reference a library project ( example is `test/FSharpTestProjects/TestApp` or `test/TestProjects/TestApp` )

the f# compiler (and dotnet-compile-fsc) doesnt create .pdb files atm (not supported, wip).

This error it's a regression because before the `dotnet build` of app+library worked ok, now the library .pdb is expected and a bad `System.IO.FileNotFoundException` expection is raised if not exists (at least that should be an error message)

A feedback, maybe it's useful to create two helper methods in this repo:

- `FileHelper.CopyRequired(source,to,errorMessage)` => raise error message if source file doesnt exists
- `FileHelper.CopyOptional(source,to)` => no error if source file doesnt exists

And review current code to use only these two, not directly `File.Copy`. 

I can trace commit but it's not important. 

What's a possible fix?

1. copy pdb only if exists
2. error message if pdb doesnt exists **and it's enabled in project.json** (it's possible to disable pdb in project.json?)

the example:

```
PS D:\github\cli\test\FSharpTestProjects\TestApp> dotnet build
Compiling TestLibrary for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.9888705
Compiling TestApp for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.4152821
System.IO.FileNotFoundException: Could not find file 'D:\github\cli\test\FSharpTestProjects\TestLibrary\bin\Debug\dnxcor
e50\TestLibrary.pdb'.
File name: 'D:\github\cli\test\FSharpTestProjects\TestLibrary\bin\Debug\dnxcore50\TestLibrary.pdb'
   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at Microsoft.DotNet.Cli.Compiler.Common.LibraryExporterExtensions.CopyTo(IEnumerable`1 assets, String destinationPath
)
   at Microsoft.Dotnet.Cli.Compiler.Common.Executable.WriteDepsFileAndCopyProjectDependencies(LibraryExporter exporter,
String projectFileName, String outputPath)
   at Microsoft.Dotnet.Cli.Compiler.Common.Executable.MakeCompilationOutputRunnableForCoreCLR(String outputPath, Library
Exporter exporter)
   at Microsoft.Dotnet.Cli.Compiler.Common.Executable.ExportRuntimeAssets(String outputPath, String configuration)
   at Microsoft.Dotnet.Cli.Compiler.Common.Executable.MakeCompilationOutputRunnable(String configuration)
   at Microsoft.DotNet.Tools.Build.CompileContext.MakeRunnableIfNecessary()
   at Microsoft.DotNet.Tools.Build.CompileContext.InvokeCompileOnRootProject()
   at Microsoft.DotNet.Tools.Build.CompileContext.Compile(Boolean incremental)
   at Microsoft.DotNet.Tools.Build.BuildCommand.<>c__DisplayClass1_0.<OnExecute>b__2(CompileContext c)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.Tools.Build.BuildCommand.OnExecute(List`1 contexts, CompilerCommandApp args)
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.<>c__DisplayClass70_0.<Execute>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.Execute(OnExecute execute, String[] args)
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args)
```

### PR DESCRIPTION
**Pull request by enricosada**
rebased fix for `dotnet-compile-fsc`.

Only `src/dotnet/commands/dotnet-compile-fsc/Program.cs` is changed to fix bugs

fix #1199 #692 and probably #1279

### CODE REVIEW

File: src/dotnet/commands/dotnet-compile-fsc/Program.cs [hunk 1]
```diff
@@ -137,6 +134,13 @@ public static int Run(string[] args)
                 File.Move(outputName, originalOutputName);
             }
 
+            //HACK dotnet build require a pdb (crash without), fsc atm cant generate a portable pdb, so an empty pdb is created
```
Comment (davidfowl) [inline src/dotnet/commands/dotnet-compile-fsc/Program.cs]: Why not change the places that expect pdbs to be on disk?

Comment (enricosada) [inline src/dotnet/commands/dotnet-compile-fsc/Program.cs]: @davidfowl initially i have done like that, as you suggested in the issue.
I ignored copy if pdb file doesnt exists, but i think it's an error if pdb doesnt exists (it's expected to exists, only f# doesnt create it atm). 
The modify was ignoring all not existing files (ignore only pdb is an hack).
Reporting an error and abort it's useless for me, i want to make f# work.
I tried to add a warning (instead of error) but the code diff was too large, and change of merge is low.

Its already a bit hard for me merge changes in `dotnet-compile-fsc` alone, so i was trying to workaround in `dotnet-compile-fsc` code without changing the rest of code in this repo. 
Maybe like that it's faster to merge (and for sure i dont want introduce bugs in c#).

**Comment by enricosada** [comment]
rebase against d18ff2f

**Comment by abrodersen** [comment]
Please merge this. I would love to start using the CLI and these fixes are necessary to do so.

**Comment by enricosada** [comment]
@abrodersen they are restoring the ci build atm, after that i think they are returning to pr backlog.

Meanwhile if you can, clone this pr branch and do `build`. i do that and works (i'll send fix to this branch until the pr is open). 

i added https://github.com/enricosada/fsharp-dotnet-cli-samples to build `latest`, `rel/1.0.0` and `this pr branch`, to check it's working

**Comment by enricosada** [comment]
rebased against d67a0cd
