### PR TITLE
Launch with apphost for `dotnet run`. 

### LINKED ISSUE #9866: dotnet run ignores `--runtime`
It doesn't actually ignore it, it passes it down as `RuntimeIdentifiers` rather than `RuntimeIdentifier`.  The result is that it restores for the RID but does nothing else with it.  I'd argue it should do the same as build.

## Steps to reproduce
1. dotnet new console.
2. dotnet build --runtime win-x64
    - notice that a win-x64 binary is produced.
3. dotnet run --runtime win-x64

## Expected  behavior
the win-x64 build is run

## Actual behavior
the project is rebuilt without a RID and that RID-less version is run.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

### PR DESCRIPTION
**Pull request by peterhuene**
This PR changes `dotnet run` to respect the runtime specified via the
`--runtime` option when querying the project for the run command and arguments.

By doing so, the run command will change to the apphost instead of using
`dotnet`.  Thus, the apphost gets executed instead of `dotnet <dll>`.

Additionally, this PR adds the `-r` short form of the `--runtime` option
so that it is consistent with the other commands.

Fixes #9866.

### CODE REVIEW

File: src/dotnet/commands/dotnet-run/RunCommandParser.cs [hunk 1]
```diff
@@ -22,6 +22,7 @@ internal static class RunCommandParser
                     (
                         configuration: o.SingleArgumentOrDefault("--configuration"),
                         framework: o.SingleArgumentOrDefault("--framework"),
+                        runtime: o.SingleArgumentOrDefault("--runtime"),
```
Comment (nguerrera) [inline src/dotnet/commands/dotnet-run/RunCommandParser.cs]: I'm missing where the following happens:

"Additionally, this PR adds the -r short form of the --runtime option so that it is consistent with the other commands."

File: src/dotnet/commands/dotnet-run/RunCommandParser.cs [hunk 2]
```diff
@@ -35,6 +36,7 @@ internal static class RunCommandParser
                     CommonOptions.HelpOption(),
                     CommonOptions.ConfigurationOption(LocalizableStrings.ConfigurationOptionDescription),
                     CommonOptions.FrameworkOption(LocalizableStrings.FrameworkOptionDescription),
+                    CommonOptions.RuntimeOption(LocalizableStrings.RuntimeOptionDescription),
```
Comment (nguerrera) [inline src/dotnet/commands/dotnet-run/RunCommandParser.cs]: >RuntimeOption [](start = 34, length = 13)

Oh, here. :)

File: src/dotnet/commands/dotnet-run/RunCommandParser.cs (hunk 1 above)
Comment (peterhuene) [reply src/dotnet/commands/dotnet-run/RunCommandParser.cs]: Yeah, I should have separated this out into its own commit.  I'm still happy to do so if we feel it's necessary.  One of those things that you run into while developing and you forget to stash, but it's related to the work you're doing so you elmoshrug.gif.

Comment (nguerrera) [reply src/dotnet/commands/dotnet-run/RunCommandParser.cs]: No worries :)
