### PR TITLE
Fix --source-feed option for tool install and update commands.

### LINKED ISSUE #9132: dotnet tool install --source-feed isn't relative
## Steps to reproduce

```console
C:\git\PowerShell\src\powershell-win-core>dotnet tool install -g pwsh --version 6.1.0-preview.1 --source-feed .\nupkg
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\NuGet.targets(114,5): error : The local source 'C:\Users\rlander\AppData\Local\Temp\xrucfdsj.yyf\nupkg' doesn't exist. [C:\Users\rlander\AppData\Local\Temp\xrucfdsj.yyf\restore.csproj]
The tool package could not be restored.
Tool 'pwsh' failed to install. You may need to specify the version using

   dotnet tool install -g pwsh --version <version>

```

## Expected  behavior

I was expecting the NuGet source to realize I wanted it to use: `C:\git\PowerShell\src\powershell-win-core\nupkg`

It uses: `'C:\Users\rlander\AppData\Local\Temp\xrucfdsj.yyf\nupkg`

Fully-qualified path works. I expect to be able to use relative paths.

## Environment data
dotnet --version
2.1.300-preview2-008530

### PR DESCRIPTION
**Pull request by peterhuene**
Commit 9cc2b7c regressed the `--source-feed`
option so that it no longer accepted relative paths.  Because the option is now
saved to the temp project file, any relative paths specified by the
`--source-feed` option were made relative to the temp project path and not from
the current working directory of where dotnet was run.

The fix is to use `Path.GetFullPath` of the `--source-feed` option, provided
the option specified was not an absolute URI.

Fixes #9132.

### CODE REVIEW

**Comment by peterhuene** [comment]
Ping @livarcocc.  This is what the fix looks like for the `tool install --source-path` issue.  Should we go ahead with the fix for 2.1.3xx?  It's a fairly useful option for tool authors.

**Comment by peterhuene** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build

**Comment by peterhuene** [comment]
@MattGertz for approval

**Issues fixed**
https://github.com/dotnet/cli/issues/9132

**Description of Issue**
A change that went into Preview 2 regressed the `--source-feed` option for `dotnet tool install` and `dotnet tool update` commands.  The option previously supported relative paths from the current working directory for `dotnet`.  The regression caused the path specified to be relative to a temp directory where the restore project was created.

**Customer Impact**
Restores the `--source-feed` option to the expected behavior of being relative to the current working directory of `dotnet`.

**Risk**
Low

**Testing**
The bug exposed a test coverage gap.  Tests were added that ensure the `--source-feed` option works for both relative and absolute URI options.

File: src/dotnet/ToolPackage/ToolPackageInstaller.cs [hunk 1]
```diff
@@ -161,7 +161,17 @@ private string JoinSourceAndOfflineCache(string[] additionalFeeds)
             var feeds = new List<string>();
             if (additionalFeeds != null)
             {
-                feeds.AddRange(additionalFeeds);
+                foreach (var feed in additionalFeeds)
+                {
+                    if (Uri.IsWellFormedUriString(feed, UriKind.Absolute))
```
Comment (JeremyKuhne) [inline src/dotnet/ToolPackage/ToolPackageInstaller.cs]: Assuming URLs are valid feeds?

File: src/dotnet/ToolPackage/ToolPackageInstaller.cs [hunk 2]
```diff
@@ -161,7 +161,17 @@ private string JoinSourceAndOfflineCache(string[] additionalFeeds)
...
+                    {
+                        feeds.Add(feed);
+                    }
+                    else
+                    {
+                        feeds.Add(Path.GetFullPath(feed));
```
Comment (JeremyKuhne) [inline src/dotnet/ToolPackage/ToolPackageInstaller.cs]: The wacky relative path on Windows is drive relative (`C:foo`). It looks like that one falls through to here, which is good. Device paths are strange too (`\\?\` & `\\.\`), but they always have to be fully qualified.

There is a new `Path.GetFullPath` that takes the base path to resolve relative paths against. It hardens against the current directory getting changed by other process threads. Consider that if you know what the base path should be.

File: src/dotnet/ToolPackage/ToolPackageInstaller.cs (hunk 1 above)
Comment (peterhuene) [reply src/dotnet/ToolPackage/ToolPackageInstaller.cs]: NuGet supports both URIs and file paths, yes.

Comment (JeremyKuhne) [reply src/dotnet/ToolPackage/ToolPackageInstaller.cs]: Thanks- presuming perf doesn't matter here. If it does, you could use `Path.IsFullyQualified()` to find items that are for sure not going to change based on the CWD. You'd still have to check Uri for false as they aren't fully qualified (from the filesystem perspective).

File: src/dotnet/ToolPackage/ToolPackageInstaller.cs (hunk 2 above)
Comment (peterhuene) [reply src/dotnet/ToolPackage/ToolPackageInstaller.cs]: The base path should be CWD in this case (at least, the CWD of `dotnet` when it was created).  `dotnet` only modifies the CWD from a legacy `dotnet migrate` scenario, as far as I know, and that doesn't impact this scenario at all.

File: src/dotnet/ToolPackage/ToolPackageInstaller.cs (hunk 1 above)
Comment (peterhuene) [reply src/dotnet/ToolPackage/ToolPackageInstaller.cs]: Thanks for the feedback.  We likely won't have more than a few of these `--source-feed` options passed on the command line as users would probably opt for an actual NuGet.config file in that case.  Do you think it'd be worth adding a `Path.IsPathFullyQualified` check to avoid a few `Path.GetFullPath` calls?
