### PR TITLE
Fix project type GUIDs when adding projects to solution files.

### LINKED ISSUE #5131: `dotnet <sln> add proj` should have good defaults for ProjectTypeGuid
@jgoshi

### LINKED ISSUE #7742: Possible mistake in ProjectInstanceExtensions
Take a look at src/dotnet/ProjectInstanceExtensions.cs line 26. 
You read a property value for "ProjectTypeGuid". But as far as I know there is only "ProjectTypeGuid**s**". 
My case - dotnet sln add command. You incorrectly retrieve project type guid and write it in a solution file.

### PR DESCRIPTION
**Pull request by peterhuene**
This PR ensures the correct property (`ProjectTypeGuids`) is respected when
adding a project to a solution file.

Additionally, we now error if a project type GUID cannot be determined rather
than incorrectly mapping to the C# project type.

Enabled previously disabled tests that were waiting on upstream changes from
MSBuild and F#.

Fixes #5131.
Fixes #7742.

### CODE REVIEW

**Comment by nguerrera** [comment]
Cc @davkean Can you review this?

File: src/dotnet/ProjectInstanceExtensions.cs [hunk 1]
```diff
@@ -22,29 +22,12 @@ public static string GetProjectId(this ProjectInstance projectInstance)
...
         {
-            string projectTypeGuid = null;
-
-            var projectTypeGuidProperty = projectInstance.GetPropertyValue("ProjectTypeGuid");
-            if (!string.IsNullOrEmpty(projectTypeGuidProperty))
-            {
-                projectTypeGuid = projectTypeGuidProperty.Split(';').Last();
-            }
-            else
+            var projectTypeGuids = projectInstance.GetPropertyValue("ProjectTypeGuids");
```
Comment (nguerrera) [inline src/dotnet/ProjectInstanceExtensions.cs]: I believe that VS actually scans for the guid using strstr. E.g. you can comment it out and it still has an impact! I believe the rationale is that a project system needn't use msbuild or even xml for its project file format. It might be worth hunting down what VS does and replicating it.

**Comment by peterhuene** [comment]
@dotnet-bot test this please

**Comment by peterhuene** [comment]
@dotnet-bot test this please

**Comment by peterhuene** [comment]
ping @davkean 😄

File: src/dotnet/ProjectInstanceExtensions.cs (hunk 1 above)
Comment (davkean) [reply src/dotnet/ProjectInstanceExtensions.cs]: Looks okay apart from this case; ProjectTypeGuids is only ever read from the project file itself. DefaultProjectTypeGuid should be read using evaluation, however.

Comment (peterhuene) [reply src/dotnet/ProjectInstanceExtensions.cs]: Is there a way to limit the evaluation scope or are you suggesting we read the project file XML and search for `ProjectTypeGuids`?

Comment (davkean) [reply src/dotnet/ProjectInstanceExtensions.cs]: Yes, we walk the construction model in other cases similar to this.

Comment (peterhuene) [reply src/dotnet/ProjectInstanceExtensions.cs]: Gotcha, I'll see if I can do it the way VS does.

Comment (davkean) [reply src/dotnet/ProjectInstanceExtensions.cs]: VS itself actually does a text scan like @nguerrera was suggesting - but walking the construction model will be good enough.

Comment (peterhuene) [reply src/dotnet/ProjectInstanceExtensions.cs]: @davkean I've pushed up reading the project type guid from the `ProjectRootElement`.  Would you remind reviewing the commit again?  Thanks!

**Comment by peterhuene** [comment]
@dotnet-bot Test RHEL6 x64 Debug Build please.

**Comment by peterhuene** [comment]
ping @davkean for one last review :)

File: src/dotnet/ProjectRootElementExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+namespace Microsoft.DotNet.Tools.Common
+{
+    public static class ProjectRootElementExtensions
+    {
+        public static string GetProjectTypeGuid(this ProjectRootElement rootElement)
+        {
+            return rootElement
+                .Properties
+                .FirstOrDefault(p => p.Name == "ProjectTypeGuids")
```
Comment (davkean) [inline src/dotnet/ProjectRootElementExtensions.cs]: Case insensitive.

Comment (peterhuene) [reply src/dotnet/ProjectRootElementExtensions.cs]: Thanks, I'll fix this and the other places we're reading properties in a case-sensitive manner.

**Comment by peterhuene** [comment]
@MattGertz for 2.1.3xx tell mode
