### PR TITLE
Changing dotnet-test options

### LINKED ISSUE #4960: dotnet test needs to have the same formatted options as the rest of the CLI
## Steps to reproduce

* Install Preview 3+ bits (MSBuild based)
* Run `dotnet test --help`

## Expected  behavior
See properly formatted options that correspond to the rest of the CLI's options, like below:

```
Options:
  -h|--help                             Show help information
  -s|--settings <SettingsFile>          Settings to use when running tests.
  -t |--list-tests                       Lists discovered tests
  --test-case-filter <Expression>    Run tests that match the given expression.
                                        Examples:
                                        --testCaseFilter:"Priority = 1"
                                        --testCaseFilter: "(FullyQualifiedName~Nightly | Name = MyTestMethod)"
  --test-adapter-path                Use custom adapters from the given path in the test run.
                                        Example: --testAdapterPath:<pathToCustomAdapters>
  -l|--logger <LoggerUri/FriendlyName>  Specify a logger for test results.
                                        Example: --logger:trx
  -c|--configuration <configuration>    Configuration under which to build, i.e. Debug/Release
  -f|--framework <FrameworkVersion>     Looks for test binaries for a specific framework
  -o|--output <OutputDir>               Directory in which to find the binaries to be run
  -d|--diag <PathToLogFile>             Enable verbose logs for test platform.
                                        Logs are written to the provided file.
  --no-build                             Do not build project before testing.
```

## Actual behavior

```
Options:
  -h|--help                             Show help information
  -s|--settings <SettingsFile>          Settings to use when running tests.
  -lt|--listTests                       Lists discovered tests
  -tcf|--testCaseFilter <Expression>    Run tests that match the given expression.
                                        Examples:
                                        --testCaseFilter:"Priority = 1"
                                        --testCaseFilter: "(FullyQualifiedName~Nightly | Name = MyTestMethod)"
  -tap|--testAdapterPath                Use custom adapters from the given path in the test run.
                                        Example: --testAdapterPath:<pathToCustomAdapters>
  -l|--logger <LoggerUri/FriendlyName>  Specify a logger for test results.
                                        Example: --logger:trx
  -c|--configuration <configuration>    Configuration under which to build, i.e. Debug/Release
  -f|--framework <FrameworkVersion>     Looks for test binaries for a specific framework
  -o|--output <OutputDir>               Directory in which to find the binaries to be run
  -d|--diag <PathToLogFile>             Enable verbose logs for test platform.
                                        Logs are written to the provided file.
  --noBuild                             Do not build project before testing.
```

I will be adding the suggested changes in a minute.

### PR DESCRIPTION
**Pull request by blackdwarf**
In Preview 3, the `dotnet test` options were not aligned with the CLI's
adopted format. This PR changes the options to be aligned. Where
possible/applicable, I have shortened the long options to a meaningful
mnemonic short version.

Fixes #4960

/cc @livarcocc @piotrpMSFT @Faizan2304

### CODE REVIEW

File: src/dotnet/commands/dotnet-test/Program.cs [hunk 1]
```diff
@@ -39,17 +39,17 @@ public static int Run(string[] args)
                 CommandOptionType.SingleValue);
 
             var listTestsOption = cmd.Option(
-                "-lt|--listTests",
+                "-t|--list-tests",
```
Comment (dasMulli) [inline src/dotnet/commands/dotnet-test/Program.cs]: @blackdwarf can this be `-l` for the verb "list" here?  I think `dotnet test -l` seems more intuitive here ("test" shows up in the verb and `-l` usually means list)

Comment (blackdwarf) [inline src/dotnet/commands/dotnet-test/Program.cs]: @dasMulli thought that as well, but `-l` is taken for the `--logger` where it seems much more natural.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please.

File: src/dotnet/commands/dotnet-test/Program.cs (hunk 1 above)
Comment (piotrpMSFT) [inline src/dotnet/commands/dotnet-test/Program.cs]: `-l` is also used for `--language` in `dotnet-new`. I don't think it's something we need to account for since both are one-offs, but worth mentioning.

**Comment by blackdwarf** [comment]
@piotrpMSFT I've cc-ed @Faizan2304 who else do I need to add?

**Comment by blackdwarf** [comment]
@dotnet-bot test OSX x64 Release please

**Comment by blackdwarf** [comment]
@dotnet-bot test OSX x64 Release Build please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX x64 Release Build please.

**Comment by codito** [comment]
:+1:
